In [1]:
import pandas as pd
import numpy as np
from scipy import stats

In [2]:
data_final = pd.read_csv('final_data.csv', sep =',', encoding='utf-8')
data_final = data_final.drop(['case:concept:name', 'concept:name', 'time:timestamp', 'hour', 'month', 'year', 'dayofweek'], axis = 1)
data_final_case = data_final.drop(['Time', 'Time_end', 'Name', 'Stage', 'duration', 'Channel'], axis = 1).drop_duplicates()
data_final_case

,ID,Time_start_case,Time_end_case,case_duration,Type,Hit,Place,Model,Price,Like,variant,word,cycle
0,П00001,2023-09-12 04:32:23+00:00,2023-09-14 14:32:23+00:00,2.416667,Личный ущерб,ДТП со скрывшимся виновником,Краснодар,Fiat 500X Trekking AWD,128860.0,3,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
10,П00002,2023-06-30 17:15:48+00:00,2023-07-03 03:20:48+00:00,2.420139,Личный ущерб,Боковое столкновение,Краснодар,Infiniti QX60 Luxe,110925.0,1,"('Регистрация претензии', 'Проверка документов...",ABJDDEFGHI,В себя: разово
20,П00003,2024-05-13 23:30:32+00:00,2024-05-14 20:33:32+00:00,0.877083,Личный ущерб,Переднее столкновение,Красноярск,Alfa Romeo Giulia Quadrifoglio,797810.0,4,"('Регистрация претензии', 'Проверка документов...",ABDEFGHI,no
28,П00004,2024-09-12 19:37:14+00:00,2024-09-13 07:46:14+00:00,0.506250,Личный ущерб,Боковое столкновение,Владивосток,Hyundai Santa Cruz SEL Premium AWD,751655.0,5,"('Регистрация претензии', 'Проверка документов...",ABDEFGHI,no
36,П00005,2024-09-08 03:58:17+00:00,2024-09-09 21:58:17+00:00,1.750000,Личный ущерб,Заднее столкновение,Екатеринбург,Jaguar XJ Ultimate,571795.0,4,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...
441503,П09995,2025-01-19 14:39:28+00:00,2025-01-21 08:39:28+00:00,1.750000,Личный ущерб,Столкновение нескольких автомобилей,Челябинск,Honda Accord Hybrid,754035.0,4,"('Регистрация претензии', 'Проверка документов...",ABDEFGHI,no
441511,П09996,2023-08-24 19:22:31+00:00,2023-08-27 05:30:31+00:00,2.422222,Ответственность перед третьими лицами,Заднее столкновение,Тюмень,Hyundai Ioniq,603840.0,3,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
441523,П09997,2023-05-22 07:36:39+00:00,2023-05-23 15:36:39+00:00,1.333333,Ответственность перед третьими лицами,Столкновение нескольких автомобилей,Барнаул,Land Rover Discovery HSE Luxury,255935.0,5,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
441532,П09998,2023-09-26 23:49:53+00:00,2023-09-27 17:53:53+00:00,0.752778,Личный ущерб,Опрокидывание автомобиля,Тольятти,Toyota Land Cruiser Heritage,2929865.0,5,"('Регистрация претензии', 'Проверка документов...",ABDKELMHI,no
441541,П09999,2024-08-08 21:17:58+00:00,2024-08-09 15:20:58+00:00,0.752083,Ответственность перед третьими лицами,Боковое столкновение,Челябинск,Lexus LX 600 AWD,526065.0,4,"('Регистрация претензии', 'Проверка документов...",ABDENFGHI,no

In [3]:
data_doc_check = data_final[data_final['Stage'] == 'Проверка документов']
data_reg_disc = data_final[data_final['Stage'] == 'Урегулирование претензии']
data_doc_check

,ID,Time_start_case,Time_end_case,case_duration,Stage,Time,Channel,Name,Type,Hit,Place,Model,Price,Like,Time_end,duration,variant,word,cycle
1,П00001,2023-09-12 04:32:23+00:00,2023-09-14 14:32:23+00:00,2.416667,Проверка документов,2023-09-12 09:32:23+00:00,Офис,Ксения Петрова,Личный ущерб,ДТП со скрывшимся виновником,Краснодар,Fiat 500X Trekking AWD,128860.0,3,2023-09-12 21:32:23+00:00,720.0,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
3,П00001,2023-09-12 04:32:23+00:00,2023-09-14 14:32:23+00:00,2.416667,Проверка документов,2023-09-12 23:32:23+00:00,Офис,Алексей Лопухин,Личный ущерб,ДТП со скрывшимся виновником,Краснодар,Fiat 500X Trekking AWD,128860.0,3,2023-09-13 11:32:23+00:00,720.0,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
11,П00002,2023-06-30 17:15:48+00:00,2023-07-03 03:20:48+00:00,2.420139,Проверка документов,2023-06-30 17:20:48+00:00,Электронная почта,Алексей Лопухин,Личный ущерб,Боковое столкновение,Краснодар,Infiniti QX60 Luxe,110925.0,1,2023-07-01 02:20:48+00:00,540.0,"('Регистрация претензии', 'Проверка документов...",ABJDDEFGHI,В себя: разово
21,П00003,2024-05-13 23:30:32+00:00,2024-05-14 20:33:32+00:00,0.877083,Проверка документов,2024-05-14 05:30:32+00:00,Офис,Анна Егорова,Личный ущерб,Переднее столкновение,Красноярск,Alfa Romeo Giulia Quadrifoglio,797810.0,4,2024-05-14 13:30:32+00:00,480.0,"('Регистрация претензии', 'Проверка документов...",ABDEFGHI,no
29,П00004,2024-09-12 19:37:14+00:00,2024-09-13 07:46:14+00:00,0.506250,Проверка документов,2024-09-13 01:37:14+00:00,Офис,Анна Егорова,Личный ущерб,Боковое столкновение,Владивосток,Hyundai Santa Cruz SEL Premium AWD,751655.0,5,2024-09-13 01:41:14+00:00,4.0,"('Регистрация претензии', 'Проверка документов...",ABDEFGHI,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441504,П09995,2025-01-19 14:39:28+00:00,2025-01-21 08:39:28+00:00,1.750000,Проверка документов,2025-01-19 20:39:28+00:00,Сайт,Геннадий Кривцов,Личный ущерб,Столкновение нескольких автомобилей,Челябинск,Honda Accord Hybrid,754035.0,4,2025-01-20 04:39:28+00:00,480.0,"('Регистрация претензии', 'Проверка документов...",ABDEFGHI,no
441512,П09996,2023-08-24 19:22:31+00:00,2023-08-27 05:30:31+00:00,2.422222,Проверка документов,2023-08-24 23:22:31+00:00,Офис,Семён Афанасьев,Ответственность перед третьими лицами,Заднее столкновение,Тюмень,Hyundai Ioniq,603840.0,3,2023-08-25 11:22:31+00:00,720.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
441524,П09997,2023-05-22 07:36:39+00:00,2023-05-23 15:36:39+00:00,1.333333,Проверка документов,2023-05-22 12:36:39+00:00,Офис,Сергей Петров,Ответственность перед третьими лицами,Столкновение нескольких автомобилей,Барнаул,Land Rover Discovery HSE Luxury,255935.0,5,2023-05-22 19:36:39+00:00,420.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
441533,П09998,2023-09-26 23:49:53+00:00,2023-09-27 17:53:53+00:00,0.752778,Проверка документов,2023-09-27 04:49:53+00:00,Телефон,Сидоров Илья,Личный ущерб,Опрокидывание автомобиля,Тольятти,Toyota Land Cruiser Heritage,2929865.0,5,2023-09-27 10:49:53+00:00,360.0,"('Регистрация претензии', 'Проверка документов...",ABDKELMHI,no
441542,П09999,2024-08-08 21:17:58+00:00,2024-08-09 15:20:58+00:00,0.752083,Проверка документов,2024-08-09 02:17:58+00:00,Офис,Денис Прохоров,Ответственность перед третьими лицами,Боковое столкновение,Челябинск,Lexus LX 600 AWD,526065.0,4,2024-08-09 08:17:58+00:00,360.0,"('Регистрация претензии', 'Проверка документов...",ABDENFGHI,no

#### Среднее время выполнения операций (этапов): Проверка документов

In [4]:
doc_check_dur = data_doc_check.groupby(['Name'])['duration'].mean().reset_index()
doc_check_dur

                   Name    duration
0       Алексей Лопухин  393.906497
1         Алёна Волкова  387.909208
2          Анна Егорова  383.144522
3     Владимир Воробьёв  385.707918
4      Геннадий Кривцов  388.863777
5        Денис Прохоров  384.006660
6   Елизавета Нестерова  387.364996
7         Инна Смирнова  377.796403
8        Ксения Петрова  390.340471
9        Леонид Куликов  386.846355
10      Михаил Трофимов  387.269677
11      Николай Кабанов  380.409766
12      Семён Афанасьев  383.310616
13        Сергей Петров  383.802849
14         Сидоров Илья  393.256861

#### Урегулирование претензии

In [5]:
doc_reg_disc = data_reg_disc.groupby(['Name'])['duration'].mean().reset_index()
doc_reg_disc

                   Name    duration
0       Алексей Лопухин  769.482931
1         Алёна Волкова  769.859764
2          Анна Егорова  772.920307
3     Владимир Воробьёв  776.637730
4      Геннадий Кривцов  772.541885
5        Денис Прохоров  768.109055
6   Елизавета Нестерова  779.849458
7         Инна Смирнова  761.555232
8        Ксения Петрова  757.920060
9        Леонид Куликов  759.711206
10      Михаил Трофимов  761.751638
11      Николай Кабанов  746.733471
12      Семён Афанасьев  779.558425
13        Сергей Петров  781.974457
14         Сидоров Илья  762.569572

#### Среднее время сотрудников на самые сложные задачи

In [6]:
data_bottle = pd.merge(doc_check_dur, doc_reg_disc, on = 'Name', suffixes=['_check', '_reg'])
data_bottle['sum'] = data_bottle['duration_check'] + data_bottle['duration_reg']
data_bottle = data_bottle.sort_values('sum')
data_bottle

                   Name  duration_check  duration_reg          sum
11      Николай Кабанов      380.409766    746.733471  1127.143238
7         Инна Смирнова      377.796403    761.555232  1139.351634
9        Леонид Куликов      386.846355    759.711206  1146.557562
8        Ксения Петрова      390.340471    757.920060  1148.260531
10      Михаил Трофимов      387.269677    761.751638  1149.021315
5        Денис Прохоров      384.006660    768.109055  1152.115716
14         Сидоров Илья      393.256861    762.569572  1155.826433
2          Анна Егорова      383.144522    772.920307  1156.064829
1         Алёна Волкова      387.909208    769.859764  1157.768972
4      Геннадий Кривцов      388.863777    772.541885  1161.405662
3     Владимир Воробьёв      385.707918    776.637730  1162.345647
12      Семён Афанасьев      383.310616    779.558425  1162.869041
0       Алексей Лопухин      393.906497    769.482931  1163.389428
13        Сергей Петров      383.802849    781.974457  1165.777307
6   Елизавета Нестерова      387.364996    779.849458  1167.214454

#### Зависимость удовлетворенности клиентов от размеров выплаты

In [7]:
like_price = data_final_case.groupby('Like')['Price'].mean()
like_price

Like
1    647501.407642
2    634009.437445
3    661183.252650
4    942617.586531
5    948069.182256
Name: Price, dtype: float64

#### Зависимость реализации кейса от канала связи

In [8]:
word_channel = data_final.groupby(['word','Channel'])['ID'].count()
word_channel

word          Channel
ABCBCBDEFGHI  Офис                  5328
              Сайт                 12024
              Телефон                384
              Электронная почта      996
ABCBDEFGHI    Офис                 10390
              Сайт                 22250
              Телефон                580
              Электронная почта     1650
ABDEFGHI      Офис                 35424
              Сайт                 75168
              Телефон               2616
              Электронная почта     5600
ABDENFGHI     Офис                 14697
              Сайт                 31104
              Телефон               1071
              Электронная почта     2466
ABDKELMHI     Офис                 20223
              Сайт                 42750
              Телефон               1251
              Электронная почта     3483
ABDKOHI       Офис                  3017
              Сайт                  6685
              Телефон                210
              Электронная почта      630
ABDOHI        Офис                  2694
              Сайт                  5490
              Телефон                186
              Электронная почта      360
ABDOPEHI      Офис                  7280
              Сайт                 14936
              Телефон                480
              Электронная почта     1352
ABJDDDDEFGHI  Офис                  5916
              Сайт                 11424
              Телефон                468
              Электронная почта     1044
ABJDDEFGHI    Офис                 15290
              Сайт                 31520
              Телефон               1050
              Электронная почта     2580
ABJDEFGHI     Офис                 11961
              Сайт                 24786
              Телефон                765
              Электронная почта     1971
Name: ID, dtype: int64

In [9]:
word_channel_percent = (word_channel / word_channel.groupby('word').transform('sum') * 100).round(2).reset_index()
pivot_word_channel = word_channel_percent.pivot_table(index = 'word', columns = 'Channel', values = 'ID', sort = False).sort_index(axis=1)
pivot_word_channel

Channel        Офис   Сайт  Телефон  Электронная почта
word
ABCBCBDEFGHI  28.44  64.19     2.05               5.32
ABCBDEFGHI    29.80  63.81     1.66               4.73
ABDEFGHI      29.82  63.27     2.20               4.71
ABDENFGHI     29.79  63.04     2.17               5.00
ABDKELMHI     29.87  63.14     1.85               5.14
ABDKOHI       28.62  63.41     1.99               5.98
ABDOHI        30.86  62.89     2.13               4.12
ABDOPEHI      30.27  62.11     2.00               5.62
ABJDDDDEFGHI  31.38  60.60     2.48               5.54
ABJDDEFGHI    30.31  62.49     2.08               5.11
ABJDEFGHI     30.29  62.78     1.94               4.99

#### Зависимость реализации кейса от типа повреждения автомобиля

In [10]:
def percent_group(df, index, columns, values):
    group_data = df.groupby([index, columns])['ID'].count()
    data_percent = (group_data / group_data.groupby(index).transform('sum') * 100).round(2).reset_index()
    pivot_data = data_percent.pivot_table(index = index, columns = columns, values = values, sort = False).sort_index(axis=1)
    return pivot_data

In [11]:
pivot_word_hit= percent_group(data_final_case, 'Hit', 'word', 'ID')
pivot_word_hit

word,ABCBCBDEFGHI,ABCBDEFGHI,ABDEFGHI,ABDENFGHI,ABDKELMHI,ABDKOHI,ABDOHI,ABDOPEHI,ABJDDDDEFGHI,ABJDDEFGHI,ABJDEFGHI
Hit,,,,,,,,,,,
Боковое столкновение,3.20,7.34,29.77,11.20,14.70,2.96,3.10,6.03,3.06,9.74,8.91
ДТП со скрывшимся виновником,2.74,7.22,30.09,11.54,15.34,2.60,2.53,5.99,3.49,9.83,8.63
Заднее столкновение,3.24,6.56,29.87,10.56,15.26,3.21,2.84,6.00,3.20,10.33,8.94
Инцидент с 1 автомобилем,2.92,7.05,30.28,10.76,15.31,3.46,2.60,5.92,3.08,10.25,8.38
Опрокидывание автомобиля,3.48,7.08,29.01,11.40,15.28,2.89,3.31,5.91,2.80,10.38,8.47
Переднее столкновение,2.75,6.93,29.98,11.15,14.86,2.85,3.05,6.27,3.24,9.91,9.00
Столкновение нескольких автомобилей,3.06,6.99,30.23,10.17,14.70,3.06,2.96,6.16,3.37,10.44,8.85
Столкновение при боковом движении,3.44,7.11,29.08,11.44,15.40,2.90,2.77,5.88,3.10,10.12,8.76

#### Зависимость реализации кейса от места подачи заявления

In [12]:
pivot_word_place= percent_group(data_final_case, 'Place', 'word', 'ID')
pivot_word_place

word,ABCBCBDEFGHI,ABCBDEFGHI,ABDEFGHI,ABDENFGHI,ABDKELMHI,ABDKOHI,ABDOHI,ABDOPEHI,ABJDDDDEFGHI,ABJDDEFGHI,ABJDEFGHI
Place,,,,,,,,,,,
Барнаул,2.83,8.04,28.88,11.31,15.16,3.43,2.96,6.20,2.29,10.61,8.29
Благовещенск,2.67,7.07,29.11,10.94,14.25,3.75,2.83,6.31,2.99,10.99,9.09
Владивосток,3.31,6.74,31.20,11.23,14.46,2.89,2.80,5.97,2.94,9.51,8.94
Екатеринбург,3.33,6.84,30.26,11.13,14.93,2.97,3.14,5.90,3.29,9.89,8.33
Ижевск,3.18,7.71,30.33,10.82,14.53,2.89,2.75,6.50,2.82,9.85,8.62
Краснодар,3.17,6.95,29.42,10.86,15.49,2.99,2.55,5.54,3.04,10.64,9.35
Красноярск,3.27,6.90,29.50,10.49,15.39,3.19,3.24,6.02,3.15,10.52,8.32
Нижний Новгород,3.03,6.62,28.91,11.49,15.25,3.12,2.76,6.30,3.28,10.62,8.62
Сочи,3.33,6.72,28.76,10.94,15.45,2.89,2.77,6.45,3.74,10.00,8.94
Тольятти,3.16,6.62,30.07,11.22,15.00,2.94,3.00,5.77,3.13,9.75,9.33
Тюмень,2.78,6.57,30.52,11.25,15.41,2.60,2.71,5.98,3.23,9.91,9.02
Челябинск,2.91,7.34,30.48,10.46,15.15,2.87,3.20,5.43,3.36,9.34,9.45

#### Распределение вариантов реализации кейса в зависимости от типа страхового случая

In [13]:
pivot_word_type= percent_group(data_final_case,'Type', 'word', 'ID')
pivot_word_type

word,ABCBCBDEFGHI,ABCBDEFGHI,ABDEFGHI,ABDENFGHI,ABDKELMHI,ABDKOHI,ABDOHI,ABDOPEHI,ABJDDDDEFGHI,ABJDDEFGHI,ABJDEFGHI
Type,,,,,,,,,,,
Личный ущерб,3.08,7.05,29.95,11.06,14.91,2.99,2.85,6.03,3.10,10.11,8.85
Ответственность перед третьими лицами,3.25,6.83,29.33,10.81,15.52,3.09,3.10,6.02,3.27,10.12,8.66

#### Зависимость удовлетворенности клиентов от типа повреждения автомобиля

In [14]:
pivot_like_hit= percent_group(data_final_case, 'Hit', 'Like', 'ID')
pivot_like_hit

Like                                     1      2     3      4      5
Hit
Боковое столкновение                 17.12  11.88  5.45  43.66  21.89
ДТП со скрывшимся виновником         16.40  11.67  5.55  44.57  21.81
Заднее столкновение                  17.47  11.27  5.52  43.06  22.68
Инцидент с 1 автомобилем             17.02  10.96  6.02  44.54  21.47
Опрокидывание автомобиля             17.44  11.62  5.45  44.53  20.97
Переднее столкновение                16.63  11.21  5.92  43.50  22.74
Столкновение нескольких автомобилей  17.31  11.71  5.94  43.43  21.59
Столкновение при боковом движении    17.05  11.50  5.75  43.41  22.28

#### Зависимость удовлетворенности клиента от типа страхового случая

In [15]:
pivot_like_type= percent_group(data_final_case, 'Type', 'Like', 'ID')
pivot_like_type

Like                                       1      2     3      4      5
Type
Личный ущерб                           17.04  11.52  5.59  43.72  22.13
Ответственность перед третьими лицами  17.29  11.31  5.88  43.56  21.96

#### Зависимость удовлетворенности от места

In [16]:
pivot_like_place= percent_group(data_final_case, 'Place', 'Like', 'ID')
pivot_like_place

Like                 1      2     3      4      5
Place
Барнаул          17.22  11.79  5.94  42.83  22.21
Благовещенск     18.44  11.59  5.55  42.71  21.71
Владивосток      15.71  11.57  5.91  44.03  22.77
Екатеринбург     17.21  11.01  6.06  44.40  21.32
Ижевск           17.37  11.01  5.80  44.47  21.35
Краснодар        17.86  11.41  5.39  42.48  22.86
Красноярск       17.19  12.66  5.17  43.78  21.20
Нижний Новгород  16.93  11.67  5.66  43.38  22.36
Сочи             17.28  11.42  5.53  43.41  22.36
Тольятти         16.70  11.12  5.35  45.14  21.69
Тюмень           16.26  10.62  5.90  44.97  22.24
Челябинск        17.17  11.23  5.81  42.40  23.38

In [17]:
like_place = data_final_case.groupby('Place')['Like'].mean()
like_place

Place
Барнаул            3.410232
Благовещенск       3.376496
Владивосток        3.465714
Екатеринбург       3.416054
Ижевск             3.414279
Краснодар          3.410688
Красноярск         3.391350
Нижний Новгород    3.425590
Сочи               3.421381
Тольятти           3.439987
Тюмень             3.463052
Челябинск          3.435818
Name: Like, dtype: float64

#### Распределение сотрудников по задачам

In [18]:
pivot_name_stage= percent_group(data_final, 'Name', 'Stage', 'ID')
pivot_name_stage

Stage,Закрытие страхового случая,Обзор произошедшего случая,Отклонение претензии,Отправка платежа,Подготовка итоговой документации,Поиск потерянной документации,Получение права на предъявление претензий от страхователя,Получение страховых резервов,Предъявление апелляции по претензии,Проверка документов,Проверка на мошенничество,Регистрация претензии,Ремонт автомобиля,Урегулирование объёма убытков,Урегулирование претензии,Утверждение претензии
Name,,,,,,,,,,,,,,,,
Алексей Лопухин,10.98,11.12,1.40,1.70,8.22,1.57,1.19,1.65,0.71,12.90,2.47,11.25,8.41,1.96,13.77,10.68
Алёна Волкова,11.68,10.99,1.31,1.60,8.11,1.49,1.23,1.69,0.73,12.93,2.58,10.81,8.09,2.01,13.65,11.11
Анна Егорова,11.28,11.32,1.39,1.73,8.24,1.44,1.26,1.82,0.67,12.67,2.39,11.36,8.28,2.05,13.59,10.50
Владимир Воробьёв,11.39,11.26,1.32,1.73,8.27,1.56,1.06,1.65,0.65,13.00,2.61,11.11,7.90,1.88,13.70,10.93
Геннадий Кривцов,11.42,11.39,1.27,1.61,8.30,1.49,1.17,1.71,0.65,12.75,2.62,11.48,7.99,1.99,13.57,10.61
Денис Прохоров,11.43,11.30,1.38,1.76,8.20,1.57,1.30,1.62,0.66,12.85,2.51,11.30,8.40,2.02,13.23,10.47
Елизавета Нестерова,11.81,11.07,1.44,1.91,8.07,1.42,1.24,1.68,0.67,12.77,2.30,11.41,8.60,2.14,13.34,10.13
Инна Смирнова,11.27,11.33,1.32,1.77,8.14,1.44,1.28,1.61,0.70,12.80,2.58,11.14,8.33,2.05,13.74,10.49
Ксения Петрова,10.92,11.30,1.16,1.68,8.32,1.48,1.20,1.86,0.63,12.49,2.63,11.63,8.37,2.19,13.47,10.67
Леонид Куликов,11.11,11.45,1.35,1.72,8.00,1.53,1.21,1.67,0.66,13.01,2.46,11.23,8.23,2.02,13.58,10.79
Михаил Трофимов,10.82,11.60,1.53,1.55,8.52,1.52,1.25,1.49,0.73,12.63,2.49,11.35,7.94,2.13,13.68,10.76
Николай Кабанов,10.38,11.23,1.51,1.70,8.87,1.32,1.46,2.03,0.71,12.94,2.50,11.76,7.50,2.00,13.29,10.79
Семён Афанасьев,11.56,11.37,1.34,1.55,8.33,1.42,1.24,1.70,0.68,12.91,2.37,11.22,8.15,2.04,13.50,10.64
Сергей Петров,11.12,11.07,1.33,1.67,8.57,1.48,1.26,1.65,0.69,12.72,2.64,11.42,8.07,2.05,13.42,10.84
Сидоров Илья,11.50,11.48,1.31,1.73,8.18,1.54,1.28,1.87,0.73,12.56,2.46,11.26,8.31,2.16,13.15,10.49

In [19]:
pivot_channel_stage= percent_group(data_final,  'Stage', 'Channel', 'ID')
pivot_channel_stage

Channel,Офис,Сайт,Телефон,Электронная почта
Stage,,,,
Закрытие страхового случая,29.94,63.01,2.06,5.00
Обзор произошедшего случая,29.94,63.01,2.06,5.00
Отклонение претензии,30.00,62.63,2.03,5.35
Отправка платежа,29.87,63.14,1.85,5.14
Подготовка итоговой документации,29.95,63.04,2.10,4.91
Поиск потерянной документации,29.16,63.99,1.85,5.01
Получение права на предъявление претензий от страхователя,29.79,63.04,2.17,5.00
Получение страховых резервов,29.87,63.14,1.85,5.14
Предъявление апелляции по претензии,30.27,62.11,2.00,5.62
Проверка документов,29.85,63.12,2.03,5.00
Проверка на мошенничество,30.46,62.33,2.08,5.13
Регистрация претензии,29.94,63.01,2.06,5.00
Ремонт автомобиля,29.95,63.04,2.10,4.91
Урегулирование объёма убытков,29.66,63.19,1.87,5.28
Урегулирование претензии,30.09,62.77,2.09,5.05
Утверждение претензии,29.95,63.00,2.05,4.99

In [20]:
like_place = data_final_case.groupby('Place')['case_duration'].mean()
like_place

Place
Барнаул            1.340183
Благовещенск       1.354140
Владивосток        1.341990
Екатеринбург       1.358373
Ижевск             1.363233
Краснодар          1.357736
Красноярск         1.367953
Нижний Новгород    1.362217
Сочи               1.365808
Тольятти           1.361093
Тюмень             1.351239
Челябинск          1.364253
Name: case_duration, dtype: float64

In [21]:
like_place = data_final_case.groupby('Hit')['case_duration'].mean()
like_place

Hit
Боковое столкновение                   1.354280
ДТП со скрывшимся виновником           1.359349
Заднее столкновение                    1.360972
Инцидент с 1 автомобилем               1.357896
Опрокидывание автомобиля               1.351744
Переднее столкновение                  1.356755
Столкновение нескольких автомобилей    1.369257
Столкновение при боковом движении      1.363127
Name: case_duration, dtype: float64

In [22]:
like_place = data_final_case.groupby('Type')['case_duration'].mean()
like_place

Type
Личный ущерб                             1.359192
Ответственность перед третьими лицами    1.357958
Name: case_duration, dtype: float64

In [23]:
word_dur = data_final_case.groupby('word')['case_duration'].mean()
word_dur

word
ABCBCBDEFGHI    1.834659
ABCBDEFGHI      1.485579
ABDEFGHI        1.174936
ABDENFGHI       1.236394
ABDKELMHI       1.234111
ABDKOHI         1.099671
ABDOHI          1.057134
ABDOPEHI        1.170878
ABJDDDDEFGHI    2.845721
ABJDDEFGHI      1.766160
ABJDEFGHI       1.395376
Name: case_duration, dtype: float64

In [24]:
word_dur = data_final_case.groupby('word')['Price'].mean()
word_dur

word
ABCBCBDEFGHI    4.591143e+05
ABCBDEFGHI      4.611710e+05
ABDEFGHI        4.687123e+05
ABDENFGHI       4.666520e+05
ABDKELMHI       2.544771e+06
ABDKOHI         2.497508e+06
ABDOHI          4.692936e+05
ABDOPEHI        4.698702e+05
ABJDDDDEFGHI    4.689411e+05
ABJDDEFGHI      4.709857e+05
ABJDEFGHI       4.641286e+05
Name: Price, dtype: float64

In [25]:
data_pp = data_final[(data_final['cycle'] == 'Пинг-Понг') & (data_final['Stage'] == 'Регистрация претензии')]
top_cadr_pp = data_pp.groupby('Name')['Time'].count().reset_index()
pivot_top_cadr= percent_group(data_pp,  'Stage', 'Name', 'ID')
pivot_top_cadr

Name,Алексей Лопухин,Алёна Волкова,Анна Егорова,Владимир Воробьёв,Геннадий Кривцов,Денис Прохоров,Елизавета Нестерова,Инна Смирнова,Ксения Петрова,Леонид Куликов,Михаил Трофимов,Николай Кабанов,Семён Афанасьев,Сергей Петров,Сидоров Илья
Stage,,,,,,,,,,,,,,,
Регистрация претензии,6.47,3.27,15.57,2.88,5.25,11.02,4.23,5.96,3.84,12.81,2.37,0.83,6.66,10.83,8.01

In [26]:
pivot_name_stage= percent_group(data_final, 'Stage', 'Name', 'ID')
pivot_name_stage

Name,Алексей Лопухин,Алёна Волкова,Анна Егорова,Владимир Воробьёв,Геннадий Кривцов,Денис Прохоров,Елизавета Нестерова,Инна Смирнова,Ксения Петрова,Леонид Куликов,Михаил Трофимов,Николай Кабанов,Семён Афанасьев,Сергей Петров,Сидоров Илья
Stage,,,,,,,,,,,,,,,
Закрытие страхового случая,7.36,4.21,15.17,3.00,5.80,11.52,4.59,6.78,3.28,11.11,2.66,0.76,6.85,9.11,7.82
Обзор произошедшего случая,7.45,3.96,15.23,2.96,5.79,11.39,4.30,6.81,3.39,11.45,2.86,0.82,6.73,9.06,7.81
Отклонение претензии,7.84,3.96,15.59,2.90,5.38,11.60,4.68,6.65,2.92,11.25,3.15,0.92,6.62,9.13,7.42
Отправка платежа,7.56,3.83,15.46,3.02,5.41,11.78,4.90,7.05,3.34,11.38,2.53,0.82,6.07,9.04,7.82
Подготовка итоговой документации,7.54,4.01,15.19,2.98,5.78,11.33,4.29,6.71,3.42,10.97,2.87,0.89,6.76,9.62,7.62
Поиск потерянной документации,7.96,4.06,14.65,3.10,5.70,11.95,4.16,6.52,3.36,11.58,2.83,0.73,6.35,9.14,7.91
Получение права на предъявление претензий от страхователя,7.28,4.03,15.41,2.54,5.40,11.91,4.38,7.00,3.28,10.98,2.79,0.97,6.69,9.41,7.92
Получение страховых резервов,7.32,4.04,16.20,2.87,5.74,10.83,4.33,6.43,3.70,11.06,2.43,0.98,6.66,8.96,8.43
Предъявление апелляции по претензии,7.88,4.36,14.90,2.83,5.49,11.08,4.32,6.99,3.13,10.94,2.99,0.86,6.69,9.35,8.18
Проверка документов,7.63,4.11,15.04,3.02,5.72,11.43,4.38,6.79,3.31,11.49,2.74,0.83,6.75,9.20,7.55
Проверка на мошенничество,7.49,4.21,14.56,3.11,6.04,11.44,4.04,7.04,3.58,11.15,2.78,0.83,6.35,9.79,7.59
Регистрация претензии,7.53,3.90,15.28,2.92,5.83,11.39,4.43,6.70,3.49,11.23,2.79,0.86,6.64,9.35,7.66
Ремонт автомобиля,7.72,4.00,15.26,2.85,5.56,11.60,4.58,6.86,3.44,11.28,2.68,0.75,6.62,9.06,7.75
Урегулирование объёма убытков,7.27,4.00,15.25,2.72,5.58,11.23,4.60,6.80,3.62,11.15,2.89,0.81,6.69,9.27,8.12
Урегулирование претензии,7.71,4.11,15.28,3.01,5.77,11.15,4.33,6.91,3.38,11.36,2.82,0.81,6.69,9.19,7.48
Утверждение претензии,7.60,4.26,15.00,3.06,5.73,11.21,4.18,6.70,3.40,11.47,2.82,0.84,6.70,9.44,7.59

## Рискованно большое участие отдельных сотрудников в кейсах

In [27]:
name_price = data_final.groupby(['Name', 'Stage'])['Price'].mean().reset_index().sort_values('Price', ascending=True)
name_price.to_csv('name_price.csv', index=False, encoding='utf-8')

In [28]:
id_name = data_final.groupby(['ID', 'Name'])['Stage'].count().reset_index()
id_name = id_name[(id_name['Stage'] > 6)]
id_name

             ID            Name  Stage
41046   П014934    Анна Егорова      7
127421  П027236    Анна Егорова      7
233948  П042430  Денис Прохоров      7
284221  П049576    Анна Егорова      7
305054   П07935    Анна Егорова      7

In [29]:
bad_check = data_final[data_final['ID'] == 'П014934']
bad_check

,ID,Time_start_case,Time_end_case,case_duration,Stage,Time,Channel,Name,Type,Hit,Place,Model,Price,Like,Time_end,duration,variant,word,cycle
56938,П014934,2024-04-04 22:39:28+00:00,2024-04-05 22:42:28+00:00,1.002083,Регистрация претензии,2024-04-04 22:39:28+00:00,Сайт,Анна Егорова,Личный ущерб,Боковое столкновение,Ижевск,Infiniti Q50 Red Sport,2885665.0,4,2024-04-05 03:39:28+00:00,300.0,"('Регистрация претензии', 'Проверка документов...",ABDKELMHI,no
56939,П014934,2024-04-04 22:39:28+00:00,2024-04-05 22:42:28+00:00,1.002083,Проверка документов,2024-04-05 03:39:28+00:00,Сайт,Сидоров Илья,Личный ущерб,Боковое столкновение,Ижевск,Infiniti Q50 Red Sport,2885665.0,4,2024-04-05 15:39:28+00:00,720.0,"('Регистрация претензии', 'Проверка документов...",ABDKELMHI,no
56940,П014934,2024-04-04 22:39:28+00:00,2024-04-05 22:42:28+00:00,1.002083,Урегулирование претензии,2024-04-05 15:39:28+00:00,Сайт,Анна Егорова,Личный ущерб,Боковое столкновение,Ижевск,Infiniti Q50 Red Sport,2885665.0,4,2024-04-05 15:42:28+00:00,3.0,"('Регистрация претензии', 'Проверка документов...",ABDKELMHI,no
56941,П014934,2024-04-04 22:39:28+00:00,2024-04-05 22:42:28+00:00,1.002083,Урегулирование объёма убытков,2024-04-05 15:42:28+00:00,Сайт,Анна Егорова,Личный ущерб,Боковое столкновение,Ижевск,Infiniti Q50 Red Sport,2885665.0,4,2024-04-05 17:42:28+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABDKELMHI,no
56942,П014934,2024-04-04 22:39:28+00:00,2024-04-05 22:42:28+00:00,1.002083,Утверждение претензии,2024-04-05 17:42:28+00:00,Сайт,Анна Егорова,Личный ущерб,Боковое столкновение,Ижевск,Infiniti Q50 Red Sport,2885665.0,4,2024-04-05 18:42:28+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABDKELMHI,no
56943,П014934,2024-04-04 22:39:28+00:00,2024-04-05 22:42:28+00:00,1.002083,Получение страховых резервов,2024-04-05 18:42:28+00:00,Сайт,Анна Егорова,Личный ущерб,Боковое столкновение,Ижевск,Infiniti Q50 Red Sport,2885665.0,4,2024-04-05 19:42:28+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABDKELMHI,no
56944,П014934,2024-04-04 22:39:28+00:00,2024-04-05 22:42:28+00:00,1.002083,Отправка платежа,2024-04-05 19:42:28+00:00,Сайт,Денис Прохоров,Личный ущерб,Боковое столкновение,Ижевск,Infiniti Q50 Red Sport,2885665.0,4,2024-04-05 21:42:28+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABDKELMHI,no
56945,П014934,2024-04-04 22:39:28+00:00,2024-04-05 22:42:28+00:00,1.002083,Закрытие страхового случая,2024-04-05 21:42:28+00:00,Сайт,Анна Егорова,Личный ущерб,Боковое столкновение,Ижевск,Infiniti Q50 Red Sport,2885665.0,4,2024-04-05 22:42:28+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABDKELMHI,no
56946,П014934,2024-04-04 22:39:28+00:00,2024-04-05 22:42:28+00:00,1.002083,Обзор произошедшего случая,2024-04-05 22:42:28+00:00,Сайт,Анна Егорова,Личный ущерб,Боковое столкновение,Ижевск,Infiniti Q50 Red Sport,2885665.0,4,2024-04-05 22:42:28+00:00,0.0,"('Регистрация претензии', 'Проверка документов...",ABDKELMHI,no

In [30]:
bad_check = data_final[data_final['ID'] == 'П027236']
bad_check

,ID,Time_start_case,Time_end_case,case_duration,Stage,Time,Channel,Name,Type,Hit,Place,Model,Price,Like,Time_end,duration,variant,word,cycle
176757,П027236,2023-08-09 11:26:22+00:00,2023-08-12 16:29:22+00:00,3.210417,Регистрация претензии,2023-08-09 11:26:22+00:00,Электронная почта,Анна Егорова,Личный ущерб,Инцидент с 1 автомобилем,Тольятти,Chevrolet Traverse,703715.0,2,2023-08-09 15:26:22+00:00,240.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
176758,П027236,2023-08-09 11:26:22+00:00,2023-08-12 16:29:22+00:00,3.210417,Проверка документов,2023-08-09 15:26:22+00:00,Электронная почта,Сергей Петров,Личный ущерб,Инцидент с 1 автомобилем,Тольятти,Chevrolet Traverse,703715.0,2,2023-08-09 21:26:22+00:00,360.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
176759,П027236,2023-08-09 11:26:22+00:00,2023-08-12 16:29:22+00:00,3.210417,Проверка на мошенничество,2023-08-09 21:26:22+00:00,Электронная почта,Анна Егорова,Личный ущерб,Инцидент с 1 автомобилем,Тольятти,Chevrolet Traverse,703715.0,2,2023-08-09 22:26:22+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
176760,П027236,2023-08-09 11:26:22+00:00,2023-08-12 16:29:22+00:00,3.210417,Урегулирование претензии,2023-08-09 22:26:22+00:00,Электронная почта,Анна Егорова,Личный ущерб,Инцидент с 1 автомобилем,Тольятти,Chevrolet Traverse,703715.0,2,2023-08-10 22:26:22+00:00,1440.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
176761,П027236,2023-08-09 11:26:22+00:00,2023-08-12 16:29:22+00:00,3.210417,Урегулирование претензии,2023-08-10 22:26:22+00:00,Электронная почта,Алексей Лопухин,Личный ущерб,Инцидент с 1 автомобилем,Тольятти,Chevrolet Traverse,703715.0,2,2023-08-11 10:26:22+00:00,720.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
176762,П027236,2023-08-09 11:26:22+00:00,2023-08-12 16:29:22+00:00,3.210417,Урегулирование претензии,2023-08-11 10:26:22+00:00,Электронная почта,Михаил Трофимов,Личный ущерб,Инцидент с 1 автомобилем,Тольятти,Chevrolet Traverse,703715.0,2,2023-08-12 10:26:22+00:00,1440.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
176763,П027236,2023-08-09 11:26:22+00:00,2023-08-12 16:29:22+00:00,3.210417,Урегулирование претензии,2023-08-12 10:26:22+00:00,Электронная почта,Анна Егорова,Личный ущерб,Инцидент с 1 автомобилем,Тольятти,Chevrolet Traverse,703715.0,2,2023-08-12 10:29:22+00:00,3.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
176764,П027236,2023-08-09 11:26:22+00:00,2023-08-12 16:29:22+00:00,3.210417,Утверждение претензии,2023-08-12 10:29:22+00:00,Электронная почта,Анна Егорова,Личный ущерб,Инцидент с 1 автомобилем,Тольятти,Chevrolet Traverse,703715.0,2,2023-08-12 12:29:22+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
176765,П027236,2023-08-09 11:26:22+00:00,2023-08-12 16:29:22+00:00,3.210417,Ремонт автомобиля,2023-08-12 12:29:22+00:00,Электронная почта,Анна Егорова,Личный ущерб,Инцидент с 1 автомобилем,Тольятти,Chevrolet Traverse,703715.0,2,2023-08-12 13:29:22+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
176766,П027236,2023-08-09 11:26:22+00:00,2023-08-12 16:29:22+00:00,3.210417,Подготовка итоговой документации,2023-08-12 13:29:22+00:00,Электронная почта,Семён Афанасьев,Личный ущерб,Инцидент с 1 автомобилем,Тольятти,Chevrolet Traverse,703715.0,2,2023-08-12 14:29:22+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
176767,П027236,2023-08-09 11:26:22+00:00,2023-08-12 16:29:22+00:00,3.210417,Закрытие страхового случая,2023-08-12 14:29:22+00:00,Электронная почта,Денис Прохоров,Личный ущерб,Инцидент с 1 автомобилем,Тольятти,Chevrolet Traverse,703715.0,2,2023-08-12 16:29:22+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
176768,П027236,2023-08-09 11:26:22+00:00,2023-08-12 16:29:22+00:00,3.210417,Обзор произошедшего случая,2023-08-12 16:29:22+00:00,Электронная почта,Анна Егорова,Личный ущерб,Инцидент с 1 автомобилем,Тольятти,Chevrolet Traverse,703715.0,2,2023-08-12 16:29:22+00:00,0.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно

In [31]:
bad_check = data_final[data_final['ID'] == 'П042430']
bad_check

,ID,Time_start_case,Time_end_case,case_duration,Stage,Time,Channel,Name,Type,Hit,Place,Model,Price,Like,Time_end,duration,variant,word,cycle
324547,П042430,2024-01-15 11:09:38+00:00,2024-01-17 06:09:38+00:00,1.791667,Регистрация претензии,2024-01-15 11:09:38+00:00,Офис,Инна Смирнова,Личный ущерб,Переднее столкновение,Екатеринбург,Ram 2500 Limited,456875.0,5,2024-01-15 14:09:38+00:00,180.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
324548,П042430,2024-01-15 11:09:38+00:00,2024-01-17 06:09:38+00:00,1.791667,Проверка документов,2024-01-15 14:09:38+00:00,Офис,Денис Прохоров,Личный ущерб,Переднее столкновение,Екатеринбург,Ram 2500 Limited,456875.0,5,2024-01-16 01:09:38+00:00,660.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
324549,П042430,2024-01-15 11:09:38+00:00,2024-01-17 06:09:38+00:00,1.791667,Проверка на мошенничество,2024-01-16 01:09:38+00:00,Офис,Денис Прохоров,Личный ущерб,Переднее столкновение,Екатеринбург,Ram 2500 Limited,456875.0,5,2024-01-16 03:09:38+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
324550,П042430,2024-01-15 11:09:38+00:00,2024-01-17 06:09:38+00:00,1.791667,Урегулирование претензии,2024-01-16 03:09:38+00:00,Офис,Денис Прохоров,Личный ущерб,Переднее столкновение,Екатеринбург,Ram 2500 Limited,456875.0,5,2024-01-17 02:09:38+00:00,1380.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
324551,П042430,2024-01-15 11:09:38+00:00,2024-01-17 06:09:38+00:00,1.791667,Утверждение претензии,2024-01-17 02:09:38+00:00,Офис,Денис Прохоров,Личный ущерб,Переднее столкновение,Екатеринбург,Ram 2500 Limited,456875.0,5,2024-01-17 03:09:38+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
324552,П042430,2024-01-15 11:09:38+00:00,2024-01-17 06:09:38+00:00,1.791667,Ремонт автомобиля,2024-01-17 03:09:38+00:00,Офис,Семён Афанасьев,Личный ущерб,Переднее столкновение,Екатеринбург,Ram 2500 Limited,456875.0,5,2024-01-17 04:09:38+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
324553,П042430,2024-01-15 11:09:38+00:00,2024-01-17 06:09:38+00:00,1.791667,Подготовка итоговой документации,2024-01-17 04:09:38+00:00,Офис,Денис Прохоров,Личный ущерб,Переднее столкновение,Екатеринбург,Ram 2500 Limited,456875.0,5,2024-01-17 05:09:38+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
324554,П042430,2024-01-15 11:09:38+00:00,2024-01-17 06:09:38+00:00,1.791667,Закрытие страхового случая,2024-01-17 05:09:38+00:00,Офис,Денис Прохоров,Личный ущерб,Переднее столкновение,Екатеринбург,Ram 2500 Limited,456875.0,5,2024-01-17 06:09:38+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
324555,П042430,2024-01-15 11:09:38+00:00,2024-01-17 06:09:38+00:00,1.791667,Обзор произошедшего случая,2024-01-17 06:09:38+00:00,Офис,Денис Прохоров,Личный ущерб,Переднее столкновение,Екатеринбург,Ram 2500 Limited,456875.0,5,2024-01-17 06:09:38+00:00,0.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no

In [32]:
bad_check = data_final[data_final['ID'] == 'П049576']
bad_check

,ID,Time_start_case,Time_end_case,case_duration,Stage,Time,Channel,Name,Type,Hit,Place,Model,Price,Like,Time_end,duration,variant,word,cycle
394263,П049576,2023-04-29 04:48:31+00:00,2023-04-30 02:51:31+00:00,0.91875,Регистрация претензии,2023-04-29 04:48:31+00:00,Сайт,Анна Егорова,Личный ущерб,Заднее столкновение,Сочи,Mitsubishi Outlander PHEV SE,599590.0,4,2023-04-29 09:48:31+00:00,300.0,"('Регистрация претензии', 'Проверка документов...",ABDOPEHI,no
394264,П049576,2023-04-29 04:48:31+00:00,2023-04-30 02:51:31+00:00,0.91875,Проверка документов,2023-04-29 09:48:31+00:00,Сайт,Анна Егорова,Личный ущерб,Заднее столкновение,Сочи,Mitsubishi Outlander PHEV SE,599590.0,4,2023-04-29 20:48:31+00:00,660.0,"('Регистрация претензии', 'Проверка документов...",ABDOPEHI,no
394265,П049576,2023-04-29 04:48:31+00:00,2023-04-30 02:51:31+00:00,0.91875,Урегулирование претензии,2023-04-29 20:48:31+00:00,Сайт,Анна Егорова,Личный ущерб,Заднее столкновение,Сочи,Mitsubishi Outlander PHEV SE,599590.0,4,2023-04-29 20:51:31+00:00,3.0,"('Регистрация претензии', 'Проверка документов...",ABDOPEHI,no
394266,П049576,2023-04-29 04:48:31+00:00,2023-04-30 02:51:31+00:00,0.91875,Отклонение претензии,2023-04-29 20:51:31+00:00,Сайт,Денис Прохоров,Личный ущерб,Заднее столкновение,Сочи,Mitsubishi Outlander PHEV SE,599590.0,4,2023-04-29 21:51:31+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABDOPEHI,no
394267,П049576,2023-04-29 04:48:31+00:00,2023-04-30 02:51:31+00:00,0.91875,Предъявление апелляции по претензии,2023-04-29 21:51:31+00:00,Сайт,Анна Егорова,Личный ущерб,Заднее столкновение,Сочи,Mitsubishi Outlander PHEV SE,599590.0,4,2023-04-29 23:51:31+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABDOPEHI,no
394268,П049576,2023-04-29 04:48:31+00:00,2023-04-30 02:51:31+00:00,0.91875,Утверждение претензии,2023-04-29 23:51:31+00:00,Сайт,Анна Егорова,Личный ущерб,Заднее столкновение,Сочи,Mitsubishi Outlander PHEV SE,599590.0,4,2023-04-30 01:51:31+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABDOPEHI,no
394269,П049576,2023-04-29 04:48:31+00:00,2023-04-30 02:51:31+00:00,0.91875,Закрытие страхового случая,2023-04-30 01:51:31+00:00,Сайт,Анна Егорова,Личный ущерб,Заднее столкновение,Сочи,Mitsubishi Outlander PHEV SE,599590.0,4,2023-04-30 02:51:31+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABDOPEHI,no
394270,П049576,2023-04-29 04:48:31+00:00,2023-04-30 02:51:31+00:00,0.91875,Обзор произошедшего случая,2023-04-30 02:51:31+00:00,Сайт,Анна Егорова,Личный ущерб,Заднее столкновение,Сочи,Mitsubishi Outlander PHEV SE,599590.0,4,2023-04-30 02:51:31+00:00,0.0,"('Регистрация претензии', 'Проверка документов...",ABDOPEHI,no

In [33]:
my_list = id_name['ID'].tolist()
n = 0
for i in my_list:
    bad_check = data_final[data_final['ID'] == i]
    if n == 0:
        final_check = bad_check
    else:
        final_check = pd.concat([final_check, bad_check])
    n += 1
final_check.to_csv('final_check.csv', index = False, encoding = 'utf-8')

In [34]:
case_percent = data_final.groupby('Stage')['ID'].count()
stage_percent = case_percent.reset_index()
stage_percent['ID'] = stage_percent['ID']*100/49873
stage_percent.to_csv('stage_percent.csv', index=False, encoding='utf-8')
stage_percent

                                                Stage          ID
0                          Закрытие страхового случая  100.000000
1                          Обзор произошедшего случая  100.000000
2                                Отклонение претензии   11.964390
3                                    Отправка платежа   15.084314
4                    Подготовка итоговой документации   72.951296
5                       Поиск потерянной документации   13.251659
6   Получение права на предъявление претензий от с...   10.991919
7                        Получение страховых резервов   15.084314
8                 Предъявление апелляции по претензии    6.027309
9                                 Проверка документов  113.251659
10                          Проверка на мошенничество   22.060032
11                              Регистрация претензии  100.000000
12                                  Ремонт автомобиля   72.951296
13                      Урегулирование объёма убытков   18.103984
14                           Урегулирование претензии  119.563692
15                              Утверждение претензии   94.062920