In [158]:
import pandas as pd
import pm4py as pm
import datetime as dt

In [159]:
data_final = pd.read_csv('final_data.csv', sep =',', encoding='utf-8')
data_final = data_final.drop(['case:concept:name', 'concept:name', 'time:timestamp', 'hour', 'month', 'year', 'dayofweek'], axis = 1)
data_final_case = data_final.drop(['Time', 'Time_end', 'Name', 'Stage', 'duration'], axis = 1).drop_duplicates()
data_final_case

,ID,Time_start_case,Time_end_case,case_duration,Channel,Type,Hit,Place,Model,Price,Like,variant,word,cycle
0,П00001,2023-09-12 04:32:23+00:00,2023-09-14 14:32:23+00:00,2.416667,Офис,Личный ущерб,ДТП со скрывшимся виновником,Краснодар,Fiat 500X Trekking AWD,128860.0,3,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
10,П00002,2023-06-30 17:15:48+00:00,2023-07-03 03:20:48+00:00,2.420139,Электронная почта,Личный ущерб,Боковое столкновение,Краснодар,Infiniti QX60 Luxe,110925.0,1,"('Регистрация претензии', 'Проверка документов...",ABJDDEFGHI,В себя: разово
20,П00003,2024-05-13 23:30:32+00:00,2024-05-14 20:33:32+00:00,0.877083,Офис,Личный ущерб,Переднее столкновение,Красноярск,Alfa Romeo Giulia Quadrifoglio,797810.0,4,"('Регистрация претензии', 'Проверка документов...",ABDEFGHI,no
28,П00004,2024-09-12 19:37:14+00:00,2024-09-13 07:46:14+00:00,0.506250,Офис,Личный ущерб,Боковое столкновение,Владивосток,Hyundai Santa Cruz SEL Premium AWD,751655.0,5,"('Регистрация претензии', 'Проверка документов...",ABDEFGHI,no
36,П00005,2024-09-08 03:58:17+00:00,2024-09-09 21:58:17+00:00,1.750000,Сайт,Личный ущерб,Заднее столкновение,Екатеринбург,Jaguar XJ Ultimate,571795.0,4,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441503,П09995,2025-01-19 14:39:28+00:00,2025-01-21 08:39:28+00:00,1.750000,Сайт,Личный ущерб,Столкновение нескольких автомобилей,Челябинск,Honda Accord Hybrid,754035.0,4,"('Регистрация претензии', 'Проверка документов...",ABDEFGHI,no
441511,П09996,2023-08-24 19:22:31+00:00,2023-08-27 05:30:31+00:00,2.422222,Офис,Ответственность перед третьими лицами,Заднее столкновение,Тюмень,Hyundai Ioniq,603840.0,3,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
441523,П09997,2023-05-22 07:36:39+00:00,2023-05-23 15:36:39+00:00,1.333333,Офис,Ответственность перед третьими лицами,Столкновение нескольких автомобилей,Барнаул,Land Rover Discovery HSE Luxury,255935.0,5,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
441532,П09998,2023-09-26 23:49:53+00:00,2023-09-27 17:53:53+00:00,0.752778,Телефон,Личный ущерб,Опрокидывание автомобиля,Тольятти,Toyota Land Cruiser Heritage,2929865.0,5,"('Регистрация претензии', 'Проверка документов...",ABDKELMHI,no
441541,П09999,2024-08-08 21:17:58+00:00,2024-08-09 15:20:58+00:00,0.752083,Офис,Ответственность перед третьими лицами,Боковое столкновение,Челябинск,Lexus LX 600 AWD,526065.0,4,"('Регистрация претензии', 'Проверка документов...",ABDENFGHI,no

#### Анализ зацикленностей по сегментам

In [160]:
data_01_no_g = data_final[(data_final['cycle'] == 'no') & (data_final['case_duration'] < 1.5) & (data_final['Like'] > 3 )]
data_01_no_g

,ID,Time_start_case,Time_end_case,case_duration,Stage,Time,Channel,Name,Type,Hit,Place,Model,Price,Like,Time_end,duration,variant,word,cycle
20,П00003,2024-05-13 23:30:32+00:00,2024-05-14 20:33:32+00:00,0.877083,Регистрация претензии,2024-05-13 23:30:32+00:00,Офис,Владимир Воробьёв,Личный ущерб,Переднее столкновение,Красноярск,Alfa Romeo Giulia Quadrifoglio,797810.0,4,2024-05-14 05:30:32+00:00,360.0,"('Регистрация претензии', 'Проверка документов...",ABDEFGHI,no
21,П00003,2024-05-13 23:30:32+00:00,2024-05-14 20:33:32+00:00,0.877083,Проверка документов,2024-05-14 05:30:32+00:00,Офис,Анна Егорова,Личный ущерб,Переднее столкновение,Красноярск,Alfa Romeo Giulia Quadrifoglio,797810.0,4,2024-05-14 13:30:32+00:00,480.0,"('Регистрация претензии', 'Проверка документов...",ABDEFGHI,no
22,П00003,2024-05-13 23:30:32+00:00,2024-05-14 20:33:32+00:00,0.877083,Урегулирование претензии,2024-05-14 13:30:32+00:00,Офис,Владимир Воробьёв,Личный ущерб,Переднее столкновение,Красноярск,Alfa Romeo Giulia Quadrifoglio,797810.0,4,2024-05-14 13:33:32+00:00,3.0,"('Регистрация претензии', 'Проверка документов...",ABDEFGHI,no
23,П00003,2024-05-13 23:30:32+00:00,2024-05-14 20:33:32+00:00,0.877083,Утверждение претензии,2024-05-14 13:33:32+00:00,Офис,Анна Егорова,Личный ущерб,Переднее столкновение,Красноярск,Alfa Romeo Giulia Quadrifoglio,797810.0,4,2024-05-14 14:33:32+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABDEFGHI,no
24,П00003,2024-05-13 23:30:32+00:00,2024-05-14 20:33:32+00:00,0.877083,Ремонт автомобиля,2024-05-14 14:33:32+00:00,Офис,Анна Егорова,Личный ущерб,Переднее столкновение,Красноярск,Alfa Romeo Giulia Quadrifoglio,797810.0,4,2024-05-14 16:33:32+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABDEFGHI,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441545,П09999,2024-08-08 21:17:58+00:00,2024-08-09 15:20:58+00:00,0.752083,Получение права на предъявление претензий от с...,2024-08-09 10:20:58+00:00,Офис,Денис Прохоров,Ответственность перед третьими лицами,Боковое столкновение,Челябинск,Lexus LX 600 AWD,526065.0,4,2024-08-09 11:20:58+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABDENFGHI,no
441546,П09999,2024-08-08 21:17:58+00:00,2024-08-09 15:20:58+00:00,0.752083,Ремонт автомобиля,2024-08-09 11:20:58+00:00,Офис,Геннадий Кривцов,Ответственность перед третьими лицами,Боковое столкновение,Челябинск,Lexus LX 600 AWD,526065.0,4,2024-08-09 12:20:58+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABDENFGHI,no
441547,П09999,2024-08-08 21:17:58+00:00,2024-08-09 15:20:58+00:00,0.752083,Подготовка итоговой документации,2024-08-09 12:20:58+00:00,Офис,Сергей Петров,Ответственность перед третьими лицами,Боковое столкновение,Челябинск,Lexus LX 600 AWD,526065.0,4,2024-08-09 13:20:58+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABDENFGHI,no
441548,П09999,2024-08-08 21:17:58+00:00,2024-08-09 15:20:58+00:00,0.752083,Закрытие страхового случая,2024-08-09 13:20:58+00:00,Офис,Елизавета Нестерова,Ответственность перед третьими лицами,Боковое столкновение,Челябинск,Lexus LX 600 AWD,526065.0,4,2024-08-09 15:20:58+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABDENFGHI,no
441549,П09999,2024-08-08 21:17:58+00:00,2024-08-09 15:20:58+00:00,0.752083,Обзор произошедшего случая,2024-08-09 15:20:58+00:00,Офис,Леонид Куликов,Ответственность перед третьими лицами,Боковое столкновение,Челябинск,Lexus LX 600 AWD,526065.0,4,2024-08-09 15:20:58+00:00,0.0,"('Регистрация претензии', 'Проверка документов...",ABDENFGHI,no

In [161]:
data_01_no_b = data_final[(data_final['cycle'] == 'no') & (data_final['case_duration'] < 1.5) & (data_final['Like'] < 4 )]
data_01_no_b

,ID,Time_start_case,Time_end_case,case_duration,Stage,Time,Channel,Name,Type,Hit,Place,Model,Price,Like,Time_end,duration,variant,word,cycle
296,П00034,2023-11-30 06:04:55+00:00,2023-12-01 12:08:55+00:00,1.252778,Регистрация претензии,2023-11-30 06:04:55+00:00,Офис,Сергей Петров,Личный ущерб,Переднее столкновение,Владивосток,Cadillac CT4,3370165.0,3,2023-11-30 09:04:55+00:00,180.0,"('Регистрация претензии', 'Проверка документов...",ABDKOHI,no
297,П00034,2023-11-30 06:04:55+00:00,2023-12-01 12:08:55+00:00,1.252778,Проверка документов,2023-11-30 09:04:55+00:00,Офис,Анна Егорова,Личный ущерб,Переднее столкновение,Владивосток,Cadillac CT4,3370165.0,3,2023-11-30 09:08:55+00:00,4.0,"('Регистрация претензии', 'Проверка документов...",ABDKOHI,no
298,П00034,2023-11-30 06:04:55+00:00,2023-12-01 12:08:55+00:00,1.252778,Урегулирование претензии,2023-11-30 09:08:55+00:00,Офис,Геннадий Кривцов,Личный ущерб,Переднее столкновение,Владивосток,Cadillac CT4,3370165.0,3,2023-12-01 07:08:55+00:00,1320.0,"('Регистрация претензии', 'Проверка документов...",ABDKOHI,no
299,П00034,2023-11-30 06:04:55+00:00,2023-12-01 12:08:55+00:00,1.252778,Урегулирование объёма убытков,2023-12-01 07:08:55+00:00,Офис,Сидоров Илья,Личный ущерб,Переднее столкновение,Владивосток,Cadillac CT4,3370165.0,3,2023-12-01 09:08:55+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABDKOHI,no
300,П00034,2023-11-30 06:04:55+00:00,2023-12-01 12:08:55+00:00,1.252778,Отклонение претензии,2023-12-01 09:08:55+00:00,Офис,Леонид Куликов,Личный ущерб,Переднее столкновение,Владивосток,Cadillac CT4,3370165.0,3,2023-12-01 11:08:55+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABDKOHI,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441403,П09984,2023-11-22 02:39:38+00:00,2023-11-23 05:42:38+00:00,1.127083,Проверка документов,2023-11-22 05:39:38+00:00,Офис,Семён Афанасьев,Личный ущерб,Опрокидывание автомобиля,Сочи,Toyota Land Cruiser,828580.0,2,2023-11-22 05:42:38+00:00,3.0,"('Регистрация претензии', 'Проверка документов...",ABDOHI,no
441404,П09984,2023-11-22 02:39:38+00:00,2023-11-23 05:42:38+00:00,1.127083,Урегулирование претензии,2023-11-22 05:42:38+00:00,Офис,Леонид Куликов,Личный ущерб,Опрокидывание автомобиля,Сочи,Toyota Land Cruiser,828580.0,2,2023-11-23 02:42:38+00:00,1260.0,"('Регистрация претензии', 'Проверка документов...",ABDOHI,no
441405,П09984,2023-11-22 02:39:38+00:00,2023-11-23 05:42:38+00:00,1.127083,Отклонение претензии,2023-11-23 02:42:38+00:00,Офис,Ксения Петрова,Личный ущерб,Опрокидывание автомобиля,Сочи,Toyota Land Cruiser,828580.0,2,2023-11-23 03:42:38+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABDOHI,no
441406,П09984,2023-11-22 02:39:38+00:00,2023-11-23 05:42:38+00:00,1.127083,Закрытие страхового случая,2023-11-23 03:42:38+00:00,Офис,Инна Смирнова,Личный ущерб,Опрокидывание автомобиля,Сочи,Toyota Land Cruiser,828580.0,2,2023-11-23 05:42:38+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABDOHI,no
441407,П09984,2023-11-22 02:39:38+00:00,2023-11-23 05:42:38+00:00,1.127083,Обзор произошедшего случая,2023-11-23 05:42:38+00:00,Офис,Денис Прохоров,Личный ущерб,Опрокидывание автомобиля,Сочи,Toyota Land Cruiser,828580.0,2,2023-11-23 05:42:38+00:00,0.0,"('Регистрация претензии', 'Проверка документов...",ABDOHI,no

In [162]:
data_01_yes_g = data_final[(data_final['cycle'] != 'no') & (data_final['case_duration'] < 1.5) & (data_final['Like'] > 3 )]
data_01_yes_g

Empty DataFrame
Columns: [ID, Time_start_case, Time_end_case, case_duration, Stage, Time, Channel, Name, Type, Hit, Place, Model, Price, Like, Time_end, duration, variant, word, cycle]
Index: []

In [163]:
data_01_yes_b = data_final[(data_final['cycle'] != 'no') & (data_final['case_duration'] < 1.5) & (data_final['Like'] < 4 )]
data_01_yes_b

,ID,Time_start_case,Time_end_case,case_duration,Stage,Time,Channel,Name,Type,Hit,Place,Model,Price,Like,Time_end,duration,variant,word,cycle
45,П00006,2024-03-09 16:11:23+00:00,2024-03-10 18:18:23+00:00,1.088194,Регистрация претензии,2024-03-09 16:11:23+00:00,Сайт,Алексей Лопухин,Личный ущерб,Боковое столкновение,Тольятти,Acura MDX Elite Package,627555.0,1,2024-03-09 20:11:23+00:00,240.0,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
46,П00006,2024-03-09 16:11:23+00:00,2024-03-10 18:18:23+00:00,1.088194,Проверка документов,2024-03-09 20:11:23+00:00,Сайт,Владимир Воробьёв,Личный ущерб,Боковое столкновение,Тольятти,Acura MDX Elite Package,627555.0,1,2024-03-09 20:15:23+00:00,4.0,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
47,П00006,2024-03-09 16:11:23+00:00,2024-03-10 18:18:23+00:00,1.088194,Поиск потерянной документации,2024-03-09 20:15:23+00:00,Сайт,Денис Прохоров,Личный ущерб,Боковое столкновение,Тольятти,Acura MDX Elite Package,627555.0,1,2024-03-09 22:15:23+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
48,П00006,2024-03-09 16:11:23+00:00,2024-03-10 18:18:23+00:00,1.088194,Проверка документов,2024-03-09 22:15:23+00:00,Сайт,Анна Егорова,Личный ущерб,Боковое столкновение,Тольятти,Acura MDX Elite Package,627555.0,1,2024-03-09 22:18:23+00:00,3.0,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
49,П00006,2024-03-09 16:11:23+00:00,2024-03-10 18:18:23+00:00,1.088194,Урегулирование претензии,2024-03-09 22:18:23+00:00,Сайт,Инна Смирнова,Личный ущерб,Боковое столкновение,Тольятти,Acura MDX Elite Package,627555.0,1,2024-03-10 11:18:23+00:00,780.0,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441311,П09973,2024-09-05 16:27:01+00:00,2024-09-06 15:35:01+00:00,0.963889,Утверждение претензии,2024-09-06 10:35:01+00:00,Сайт,Ксения Петрова,Личный ущерб,Столкновение при боковом движении,Сочи,Alfa Romeo 4C Spider 2024,532525.0,1,2024-09-06 12:35:01+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABJDDEFGHI,В себя: разово
441312,П09973,2024-09-05 16:27:01+00:00,2024-09-06 15:35:01+00:00,0.963889,Ремонт автомобиля,2024-09-06 12:35:01+00:00,Сайт,Сергей Петров,Личный ущерб,Столкновение при боковом движении,Сочи,Alfa Romeo 4C Spider 2024,532525.0,1,2024-09-06 13:35:01+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABJDDEFGHI,В себя: разово
441313,П09973,2024-09-05 16:27:01+00:00,2024-09-06 15:35:01+00:00,0.963889,Подготовка итоговой документации,2024-09-06 13:35:01+00:00,Сайт,Анна Егорова,Личный ущерб,Столкновение при боковом движении,Сочи,Alfa Romeo 4C Spider 2024,532525.0,1,2024-09-06 14:35:01+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABJDDEFGHI,В себя: разово
441314,П09973,2024-09-05 16:27:01+00:00,2024-09-06 15:35:01+00:00,0.963889,Закрытие страхового случая,2024-09-06 14:35:01+00:00,Сайт,Сергей Петров,Личный ущерб,Столкновение при боковом движении,Сочи,Alfa Romeo 4C Spider 2024,532525.0,1,2024-09-06 15:35:01+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABJDDEFGHI,В себя: разово
441315,П09973,2024-09-05 16:27:01+00:00,2024-09-06 15:35:01+00:00,0.963889,Обзор произошедшего случая,2024-09-06 15:35:01+00:00,Сайт,Анна Егорова,Личный ущерб,Столкновение при боковом движении,Сочи,Alfa Romeo 4C Spider 2024,532525.0,1,2024-09-06 15:35:01+00:00,0.0,"('Регистрация претензии', 'Проверка документов...",ABJDDEFGHI,В себя: разово

In [164]:
data_12_no_g = data_final[(data_final['cycle'] == 'no') & (data_final['case_duration'] >= 1.5) & (data_final['case_duration'] < 2) & (data_final['Like'] > 3 )]
data_12_no_g

,ID,Time_start_case,Time_end_case,case_duration,Stage,Time,Channel,Name,Type,Hit,Place,Model,Price,Like,Time_end,duration,variant,word,cycle
36,П00005,2024-09-08 03:58:17+00:00,2024-09-09 21:58:17+00:00,1.75,Регистрация претензии,2024-09-08 03:58:17+00:00,Сайт,Анна Егорова,Личный ущерб,Заднее столкновение,Екатеринбург,Jaguar XJ Ultimate,571795.0,4,2024-09-08 07:58:17+00:00,240.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
37,П00005,2024-09-08 03:58:17+00:00,2024-09-09 21:58:17+00:00,1.75,Проверка документов,2024-09-08 07:58:17+00:00,Сайт,Семён Афанасьев,Личный ущерб,Заднее столкновение,Екатеринбург,Jaguar XJ Ultimate,571795.0,4,2024-09-08 18:58:17+00:00,660.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
38,П00005,2024-09-08 03:58:17+00:00,2024-09-09 21:58:17+00:00,1.75,Проверка на мошенничество,2024-09-08 18:58:17+00:00,Сайт,Леонид Куликов,Личный ущерб,Заднее столкновение,Екатеринбург,Jaguar XJ Ultimate,571795.0,4,2024-09-08 19:58:17+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
39,П00005,2024-09-08 03:58:17+00:00,2024-09-09 21:58:17+00:00,1.75,Урегулирование претензии,2024-09-08 19:58:17+00:00,Сайт,Алексей Лопухин,Личный ущерб,Заднее столкновение,Екатеринбург,Jaguar XJ Ultimate,571795.0,4,2024-09-09 15:58:17+00:00,1200.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
40,П00005,2024-09-08 03:58:17+00:00,2024-09-09 21:58:17+00:00,1.75,Утверждение претензии,2024-09-09 15:58:17+00:00,Сайт,Алёна Волкова,Личный ущерб,Заднее столкновение,Екатеринбург,Jaguar XJ Ultimate,571795.0,4,2024-09-09 16:58:17+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441506,П09995,2025-01-19 14:39:28+00:00,2025-01-21 08:39:28+00:00,1.75,Утверждение претензии,2025-01-21 03:39:28+00:00,Сайт,Алексей Лопухин,Личный ущерб,Столкновение нескольких автомобилей,Челябинск,Honda Accord Hybrid,754035.0,4,2025-01-21 05:39:28+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABDEFGHI,no
441507,П09995,2025-01-19 14:39:28+00:00,2025-01-21 08:39:28+00:00,1.75,Ремонт автомобиля,2025-01-21 05:39:28+00:00,Сайт,Сергей Петров,Личный ущерб,Столкновение нескольких автомобилей,Челябинск,Honda Accord Hybrid,754035.0,4,2025-01-21 06:39:28+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABDEFGHI,no
441508,П09995,2025-01-19 14:39:28+00:00,2025-01-21 08:39:28+00:00,1.75,Подготовка итоговой документации,2025-01-21 06:39:28+00:00,Сайт,Алексей Лопухин,Личный ущерб,Столкновение нескольких автомобилей,Челябинск,Honda Accord Hybrid,754035.0,4,2025-01-21 07:39:28+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABDEFGHI,no
441509,П09995,2025-01-19 14:39:28+00:00,2025-01-21 08:39:28+00:00,1.75,Закрытие страхового случая,2025-01-21 07:39:28+00:00,Сайт,Леонид Куликов,Личный ущерб,Столкновение нескольких автомобилей,Челябинск,Honda Accord Hybrid,754035.0,4,2025-01-21 08:39:28+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABDEFGHI,no
441510,П09995,2025-01-19 14:39:28+00:00,2025-01-21 08:39:28+00:00,1.75,Обзор произошедшего случая,2025-01-21 08:39:28+00:00,Сайт,Елизавета Нестерова,Личный ущерб,Столкновение нескольких автомобилей,Челябинск,Honda Accord Hybrid,754035.0,4,2025-01-21 08:39:28+00:00,0.0,"('Регистрация претензии', 'Проверка документов...",ABDEFGHI,no

In [165]:
data_12_no_b = data_final[(data_final['cycle'] == 'no') & (data_final['case_duration'] >= 1.5) & (data_final['case_duration'] < 2) & (data_final['Like'] < 4 )]
data_12_no_b

,ID,Time_start_case,Time_end_case,case_duration,Stage,Time,Channel,Name,Type,Hit,Place,Model,Price,Like,Time_end,duration,variant,word,cycle
614,П00070,2023-09-04 16:55:40+00:00,2023-09-06 10:55:40+00:00,1.750000,Регистрация претензии,2023-09-04 16:55:40+00:00,Сайт,Инна Смирнова,Личный ущерб,Боковое столкновение,Сочи,Chevrolet Bolt EV Premier,3807320.0,1,2023-09-04 22:55:40+00:00,360.0,"('Регистрация претензии', 'Проверка документов...",ABDKOHI,no
615,П00070,2023-09-04 16:55:40+00:00,2023-09-06 10:55:40+00:00,1.750000,Проверка документов,2023-09-04 22:55:40+00:00,Сайт,Геннадий Кривцов,Личный ущерб,Боковое столкновение,Сочи,Chevrolet Bolt EV Premier,3807320.0,1,2023-09-05 08:55:40+00:00,600.0,"('Регистрация претензии', 'Проверка документов...",ABDKOHI,no
616,П00070,2023-09-04 16:55:40+00:00,2023-09-06 10:55:40+00:00,1.750000,Урегулирование претензии,2023-09-05 08:55:40+00:00,Сайт,Инна Смирнова,Личный ущерб,Боковое столкновение,Сочи,Chevrolet Bolt EV Premier,3807320.0,1,2023-09-06 04:55:40+00:00,1200.0,"('Регистрация претензии', 'Проверка документов...",ABDKOHI,no
617,П00070,2023-09-04 16:55:40+00:00,2023-09-06 10:55:40+00:00,1.750000,Урегулирование объёма убытков,2023-09-06 04:55:40+00:00,Сайт,Елизавета Нестерова,Личный ущерб,Боковое столкновение,Сочи,Chevrolet Bolt EV Premier,3807320.0,1,2023-09-06 06:55:40+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABDKOHI,no
618,П00070,2023-09-04 16:55:40+00:00,2023-09-06 10:55:40+00:00,1.750000,Отклонение претензии,2023-09-06 06:55:40+00:00,Сайт,Ксения Петрова,Личный ущерб,Боковое столкновение,Сочи,Chevrolet Bolt EV Premier,3807320.0,1,2023-09-06 08:55:40+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABDKOHI,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441498,П09994,2024-02-14 13:27:00+00:00,2024-02-16 08:27:00+00:00,1.791667,Утверждение претензии,2024-02-16 02:27:00+00:00,Сайт,Денис Прохоров,Ответственность перед третьими лицами,Боковое столкновение,Ижевск,Tesla Cybertruck Performance,101235.0,1,2024-02-16 03:27:00+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
441499,П09994,2024-02-14 13:27:00+00:00,2024-02-16 08:27:00+00:00,1.791667,Ремонт автомобиля,2024-02-16 03:27:00+00:00,Сайт,Денис Прохоров,Ответственность перед третьими лицами,Боковое столкновение,Ижевск,Tesla Cybertruck Performance,101235.0,1,2024-02-16 05:27:00+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
441500,П09994,2024-02-14 13:27:00+00:00,2024-02-16 08:27:00+00:00,1.791667,Подготовка итоговой документации,2024-02-16 05:27:00+00:00,Сайт,Сидоров Илья,Ответственность перед третьими лицами,Боковое столкновение,Ижевск,Tesla Cybertruck Performance,101235.0,1,2024-02-16 07:27:00+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
441501,П09994,2024-02-14 13:27:00+00:00,2024-02-16 08:27:00+00:00,1.791667,Закрытие страхового случая,2024-02-16 07:27:00+00:00,Сайт,Сидоров Илья,Ответственность перед третьими лицами,Боковое столкновение,Ижевск,Tesla Cybertruck Performance,101235.0,1,2024-02-16 08:27:00+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
441502,П09994,2024-02-14 13:27:00+00:00,2024-02-16 08:27:00+00:00,1.791667,Обзор произошедшего случая,2024-02-16 08:27:00+00:00,Сайт,Леонид Куликов,Ответственность перед третьими лицами,Боковое столкновение,Ижевск,Tesla Cybertruck Performance,101235.0,1,2024-02-16 08:27:00+00:00,0.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no

In [166]:
data_12_yes_g = data_final[(data_final['cycle'] != 'no') & (data_final['case_duration'] >= 1.5) & (data_final['case_duration'] < 2) & (data_final['Like'] > 3 )]
data_12_yes_g

Empty DataFrame
Columns: [ID, Time_start_case, Time_end_case, case_duration, Stage, Time, Channel, Name, Type, Hit, Place, Model, Price, Like, Time_end, duration, variant, word, cycle]
Index: []

In [167]:
data_12_yes_b = data_final[(data_final['cycle'] != 'no') & (data_final['case_duration'] >= 1.5) & (data_final['case_duration'] < 2) & (data_final['Like'] < 4 )]
data_12_yes_b

,ID,Time_start_case,Time_end_case,case_duration,Stage,Time,Channel,Name,Type,Hit,Place,Model,Price,Like,Time_end,duration,variant,word,cycle
116,П00014,2023-03-23 15:23:24+00:00,2023-03-25 05:29:24+00:00,1.587500,Регистрация претензии,2023-03-23 15:23:24+00:00,Сайт,Сидоров Илья,Личный ущерб,Заднее столкновение,Благовещенск,GMC Acadia,318665.0,2,2023-03-23 15:27:24+00:00,4.0,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
117,П00014,2023-03-23 15:23:24+00:00,2023-03-25 05:29:24+00:00,1.587500,Проверка документов,2023-03-23 15:27:24+00:00,Сайт,Леонид Куликов,Личный ущерб,Заднее столкновение,Благовещенск,GMC Acadia,318665.0,2,2023-03-23 22:27:24+00:00,420.0,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
118,П00014,2023-03-23 15:23:24+00:00,2023-03-25 05:29:24+00:00,1.587500,Поиск потерянной документации,2023-03-23 22:27:24+00:00,Сайт,Инна Смирнова,Личный ущерб,Заднее столкновение,Благовещенск,GMC Acadia,318665.0,2,2023-03-23 23:27:24+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
119,П00014,2023-03-23 15:23:24+00:00,2023-03-25 05:29:24+00:00,1.587500,Проверка документов,2023-03-23 23:27:24+00:00,Сайт,Владимир Воробьёв,Личный ущерб,Заднее столкновение,Благовещенск,GMC Acadia,318665.0,2,2023-03-23 23:29:24+00:00,2.0,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
120,П00014,2023-03-23 15:23:24+00:00,2023-03-25 05:29:24+00:00,1.587500,Урегулирование претензии,2023-03-23 23:29:24+00:00,Сайт,Леонид Куликов,Личный ущерб,Заднее столкновение,Благовещенск,GMC Acadia,318665.0,2,2023-03-24 23:29:24+00:00,1440.0,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441479,П09992,2024-07-19 05:33:48+00:00,2024-07-21 04:36:48+00:00,1.960417,Утверждение претензии,2024-07-20 22:36:48+00:00,Офис,Денис Прохоров,Личный ущерб,Столкновение при боковом движении,Ижевск,Tesla Model S Plaid Long Range,841245.0,1,2024-07-20 23:36:48+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
441480,П09992,2024-07-19 05:33:48+00:00,2024-07-21 04:36:48+00:00,1.960417,Ремонт автомобиля,2024-07-20 23:36:48+00:00,Офис,Анна Егорова,Личный ущерб,Столкновение при боковом движении,Ижевск,Tesla Model S Plaid Long Range,841245.0,1,2024-07-21 01:36:48+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
441481,П09992,2024-07-19 05:33:48+00:00,2024-07-21 04:36:48+00:00,1.960417,Подготовка итоговой документации,2024-07-21 01:36:48+00:00,Офис,Денис Прохоров,Личный ущерб,Столкновение при боковом движении,Ижевск,Tesla Model S Plaid Long Range,841245.0,1,2024-07-21 03:36:48+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
441482,П09992,2024-07-19 05:33:48+00:00,2024-07-21 04:36:48+00:00,1.960417,Закрытие страхового случая,2024-07-21 03:36:48+00:00,Офис,Денис Прохоров,Личный ущерб,Столкновение при боковом движении,Ижевск,Tesla Model S Plaid Long Range,841245.0,1,2024-07-21 04:36:48+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
441483,П09992,2024-07-19 05:33:48+00:00,2024-07-21 04:36:48+00:00,1.960417,Обзор произошедшего случая,2024-07-21 04:36:48+00:00,Офис,Сергей Петров,Личный ущерб,Столкновение при боковом движении,Ижевск,Tesla Model S Plaid Long Range,841245.0,1,2024-07-21 04:36:48+00:00,0.0,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат

In [168]:
data_23_no_b = data_final[(data_final['cycle'] == 'no') & (data_final['case_duration'] >= 2) & (data_final['case_duration'] < 3) & (data_final['Like'] < 4 )]
data_23_no_b

,ID,Time_start_case,Time_end_case,case_duration,Stage,Time,Channel,Name,Type,Hit,Place,Model,Price,Like,Time_end,duration,variant,word,cycle
8874,П010006,2024-05-06 19:04:47+00:00,2024-05-08 21:04:47+00:00,2.083333,Регистрация претензии,2024-05-06 19:04:47+00:00,Сайт,Леонид Куликов,Личный ущерб,Переднее столкновение,Краснодар,Land Rover Range Rover Autobiography AWD,275570.0,3,2024-05-07 01:04:47+00:00,360.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
8875,П010006,2024-05-06 19:04:47+00:00,2024-05-08 21:04:47+00:00,2.083333,Проверка документов,2024-05-07 01:04:47+00:00,Сайт,Денис Прохоров,Личный ущерб,Переднее столкновение,Краснодар,Land Rover Range Rover Autobiography AWD,275570.0,3,2024-05-07 12:04:47+00:00,660.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
8876,П010006,2024-05-06 19:04:47+00:00,2024-05-08 21:04:47+00:00,2.083333,Проверка на мошенничество,2024-05-07 12:04:47+00:00,Сайт,Елизавета Нестерова,Личный ущерб,Переднее столкновение,Краснодар,Land Rover Range Rover Autobiography AWD,275570.0,3,2024-05-07 14:04:47+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
8877,П010006,2024-05-06 19:04:47+00:00,2024-05-08 21:04:47+00:00,2.083333,Урегулирование претензии,2024-05-07 14:04:47+00:00,Сайт,Михаил Трофимов,Личный ущерб,Переднее столкновение,Краснодар,Land Rover Range Rover Autobiography AWD,275570.0,3,2024-05-08 14:04:47+00:00,1440.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
8878,П010006,2024-05-06 19:04:47+00:00,2024-05-08 21:04:47+00:00,2.083333,Утверждение претензии,2024-05-08 14:04:47+00:00,Сайт,Денис Прохоров,Личный ущерб,Переднее столкновение,Краснодар,Land Rover Range Rover Autobiography AWD,275570.0,3,2024-05-08 16:04:47+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
434193,П09169,2023-03-02 03:51:29+00:00,2023-03-04 03:51:29+00:00,2.000000,Утверждение претензии,2023-03-03 20:51:29+00:00,Телефон,Сидоров Илья,Личный ущерб,Опрокидывание автомобиля,Благовещенск,Chevrolet Sonic,758285.0,1,2023-03-03 21:51:29+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
434194,П09169,2023-03-02 03:51:29+00:00,2023-03-04 03:51:29+00:00,2.000000,Ремонт автомобиля,2023-03-03 21:51:29+00:00,Телефон,Геннадий Кривцов,Личный ущерб,Опрокидывание автомобиля,Благовещенск,Chevrolet Sonic,758285.0,1,2023-03-03 23:51:29+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
434195,П09169,2023-03-02 03:51:29+00:00,2023-03-04 03:51:29+00:00,2.000000,Подготовка итоговой документации,2023-03-03 23:51:29+00:00,Телефон,Анна Егорова,Личный ущерб,Опрокидывание автомобиля,Благовещенск,Chevrolet Sonic,758285.0,1,2023-03-04 01:51:29+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
434196,П09169,2023-03-02 03:51:29+00:00,2023-03-04 03:51:29+00:00,2.000000,Закрытие страхового случая,2023-03-04 01:51:29+00:00,Телефон,Сергей Петров,Личный ущерб,Опрокидывание автомобиля,Благовещенск,Chevrolet Sonic,758285.0,1,2023-03-04 03:51:29+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no
434197,П09169,2023-03-02 03:51:29+00:00,2023-03-04 03:51:29+00:00,2.000000,Обзор произошедшего случая,2023-03-04 03:51:29+00:00,Телефон,Сидоров Илья,Личный ущерб,Опрокидывание автомобиля,Благовещенск,Chevrolet Sonic,758285.0,1,2023-03-04 03:51:29+00:00,0.0,"('Регистрация претензии', 'Проверка документов...",ABJDEFGHI,no

In [169]:
data_23_no_g = data_final[(data_final['cycle'] == 'no') & (data_final['case_duration'] >= 2) & (data_final['case_duration'] < 3) & (data_final['Like'] > 3 )]
data_23_no_g

,ID,Time_start_case,Time_end_case,case_duration,Stage,Time,Channel,Name,Type,Hit,Place,Model,Price,Like,Time_end,duration,variant,word,cycle
2681,П00305,2024-03-07 19:08:14+00:00,2024-03-09 19:08:14+00:00,2.000000,Регистрация претензии,2024-03-07 19:08:14+00:00,Сайт,Денис Прохоров,Личный ущерб,Боковое столкновение,Владивосток,Honda Passport Elite AWD,3432980.0,5,2024-03-08 01:08:14+00:00,360.0,"('Регистрация претензии', 'Проверка документов...",ABDKELMHI,no
2682,П00305,2024-03-07 19:08:14+00:00,2024-03-09 19:08:14+00:00,2.000000,Проверка документов,2024-03-08 01:08:14+00:00,Сайт,Инна Смирнова,Личный ущерб,Боковое столкновение,Владивосток,Honda Passport Elite AWD,3432980.0,5,2024-03-08 11:08:14+00:00,600.0,"('Регистрация претензии', 'Проверка документов...",ABDKELMHI,no
2683,П00305,2024-03-07 19:08:14+00:00,2024-03-09 19:08:14+00:00,2.000000,Урегулирование претензии,2024-03-08 11:08:14+00:00,Сайт,Леонид Куликов,Личный ущерб,Боковое столкновение,Владивосток,Honda Passport Elite AWD,3432980.0,5,2024-03-09 10:08:14+00:00,1380.0,"('Регистрация претензии', 'Проверка документов...",ABDKELMHI,no
2684,П00305,2024-03-07 19:08:14+00:00,2024-03-09 19:08:14+00:00,2.000000,Урегулирование объёма убытков,2024-03-09 10:08:14+00:00,Сайт,Инна Смирнова,Личный ущерб,Боковое столкновение,Владивосток,Honda Passport Elite AWD,3432980.0,5,2024-03-09 12:08:14+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABDKELMHI,no
2685,П00305,2024-03-07 19:08:14+00:00,2024-03-09 19:08:14+00:00,2.000000,Утверждение претензии,2024-03-09 12:08:14+00:00,Сайт,Денис Прохоров,Личный ущерб,Боковое столкновение,Владивосток,Honda Passport Elite AWD,3432980.0,5,2024-03-09 13:08:14+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABDKELMHI,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
436527,П09433,2023-02-27 21:57:13+00:00,2023-03-01 23:57:13+00:00,2.083333,Утверждение претензии,2023-03-01 15:57:13+00:00,Сайт,Анна Егорова,Личный ущерб,Заднее столкновение,Тольятти,Lexus LC 500,4207075.0,5,2023-03-01 17:57:13+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABDKELMHI,no
436528,П09433,2023-02-27 21:57:13+00:00,2023-03-01 23:57:13+00:00,2.083333,Получение страховых резервов,2023-03-01 17:57:13+00:00,Сайт,Елизавета Нестерова,Личный ущерб,Заднее столкновение,Тольятти,Lexus LC 500,4207075.0,5,2023-03-01 19:57:13+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABDKELMHI,no
436529,П09433,2023-02-27 21:57:13+00:00,2023-03-01 23:57:13+00:00,2.083333,Отправка платежа,2023-03-01 19:57:13+00:00,Сайт,Геннадий Кривцов,Личный ущерб,Заднее столкновение,Тольятти,Lexus LC 500,4207075.0,5,2023-03-01 21:57:13+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABDKELMHI,no
436530,П09433,2023-02-27 21:57:13+00:00,2023-03-01 23:57:13+00:00,2.083333,Закрытие страхового случая,2023-03-01 21:57:13+00:00,Сайт,Ксения Петрова,Личный ущерб,Заднее столкновение,Тольятти,Lexus LC 500,4207075.0,5,2023-03-01 23:57:13+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABDKELMHI,no
436531,П09433,2023-02-27 21:57:13+00:00,2023-03-01 23:57:13+00:00,2.083333,Обзор произошедшего случая,2023-03-01 23:57:13+00:00,Сайт,Леонид Куликов,Личный ущерб,Заднее столкновение,Тольятти,Lexus LC 500,4207075.0,5,2023-03-01 23:57:13+00:00,0.0,"('Регистрация претензии', 'Проверка документов...",ABDKELMHI,no

In [170]:
data_23_yes_b = data_final[(data_final['cycle'] != 'no') & (data_final['case_duration'] >= 2) & (data_final['case_duration'] < 3) & (data_final['Like'] < 4 )]
data_23_yes_b

,ID,Time_start_case,Time_end_case,case_duration,Stage,Time,Channel,Name,Type,Hit,Place,Model,Price,Like,Time_end,duration,variant,word,cycle
0,П00001,2023-09-12 04:32:23+00:00,2023-09-14 14:32:23+00:00,2.416667,Регистрация претензии,2023-09-12 04:32:23+00:00,Офис,Денис Прохоров,Личный ущерб,ДТП со скрывшимся виновником,Краснодар,Fiat 500X Trekking AWD,128860.0,3,2023-09-12 09:32:23+00:00,300.0,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
1,П00001,2023-09-12 04:32:23+00:00,2023-09-14 14:32:23+00:00,2.416667,Проверка документов,2023-09-12 09:32:23+00:00,Офис,Ксения Петрова,Личный ущерб,ДТП со скрывшимся виновником,Краснодар,Fiat 500X Trekking AWD,128860.0,3,2023-09-12 21:32:23+00:00,720.0,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
2,П00001,2023-09-12 04:32:23+00:00,2023-09-14 14:32:23+00:00,2.416667,Поиск потерянной документации,2023-09-12 21:32:23+00:00,Офис,Алексей Лопухин,Личный ущерб,ДТП со скрывшимся виновником,Краснодар,Fiat 500X Trekking AWD,128860.0,3,2023-09-12 23:32:23+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
3,П00001,2023-09-12 04:32:23+00:00,2023-09-14 14:32:23+00:00,2.416667,Проверка документов,2023-09-12 23:32:23+00:00,Офис,Алексей Лопухин,Личный ущерб,ДТП со скрывшимся виновником,Краснодар,Fiat 500X Trekking AWD,128860.0,3,2023-09-13 11:32:23+00:00,720.0,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
4,П00001,2023-09-12 04:32:23+00:00,2023-09-14 14:32:23+00:00,2.416667,Урегулирование претензии,2023-09-13 11:32:23+00:00,Офис,Сидоров Илья,Личный ущерб,ДТП со скрывшимся виновником,Краснодар,Fiat 500X Trekking AWD,128860.0,3,2023-09-14 07:32:23+00:00,1200.0,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441518,П09996,2023-08-24 19:22:31+00:00,2023-08-27 05:30:31+00:00,2.422222,Утверждение претензии,2023-08-26 23:30:31+00:00,Офис,Алексей Лопухин,Ответственность перед третьими лицами,Заднее столкновение,Тюмень,Hyundai Ioniq,603840.0,3,2023-08-27 00:30:31+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
441519,П09996,2023-08-24 19:22:31+00:00,2023-08-27 05:30:31+00:00,2.422222,Ремонт автомобиля,2023-08-27 00:30:31+00:00,Офис,Инна Смирнова,Ответственность перед третьими лицами,Заднее столкновение,Тюмень,Hyundai Ioniq,603840.0,3,2023-08-27 02:30:31+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
441520,П09996,2023-08-24 19:22:31+00:00,2023-08-27 05:30:31+00:00,2.422222,Подготовка итоговой документации,2023-08-27 02:30:31+00:00,Офис,Алексей Лопухин,Ответственность перед третьими лицами,Заднее столкновение,Тюмень,Hyundai Ioniq,603840.0,3,2023-08-27 04:30:31+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
441521,П09996,2023-08-24 19:22:31+00:00,2023-08-27 05:30:31+00:00,2.422222,Закрытие страхового случая,2023-08-27 04:30:31+00:00,Офис,Алёна Волкова,Ответственность перед третьими лицами,Заднее столкновение,Тюмень,Hyundai Ioniq,603840.0,3,2023-08-27 05:30:31+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
441522,П09996,2023-08-24 19:22:31+00:00,2023-08-27 05:30:31+00:00,2.422222,Обзор произошедшего случая,2023-08-27 05:30:31+00:00,Офис,Семён Афанасьев,Ответственность перед третьими лицами,Заднее столкновение,Тюмень,Hyundai Ioniq,603840.0,3,2023-08-27 05:30:31+00:00,0.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно

In [171]:
data_23_yes_g = data_final[(data_final['cycle'] != 'no') & (data_final['case_duration'] >= 2) & (data_final['case_duration'] < 3) & (data_final['Like'] > 3 )]
data_23_yes_g

Empty DataFrame
Columns: [ID, Time_start_case, Time_end_case, case_duration, Stage, Time, Channel, Name, Type, Hit, Place, Model, Price, Like, Time_end, duration, variant, word, cycle]
Index: []

In [172]:
data_30_no_g = data_final[(data_final['cycle'] == 'no') & (data_final['case_duration'] >= 3) & (data_final['Like'] > 3 )]
data_30_no_g

Empty DataFrame
Columns: [ID, Time_start_case, Time_end_case, case_duration, Stage, Time, Channel, Name, Type, Hit, Place, Model, Price, Like, Time_end, duration, variant, word, cycle]
Index: []

In [173]:
data_30_no_b = data_final[(data_final['cycle'] == 'no') & (data_final['case_duration'] >= 3) & (data_final['Like'] < 4)]
data_30_no_b

Empty DataFrame
Columns: [ID, Time_start_case, Time_end_case, case_duration, Stage, Time, Channel, Name, Type, Hit, Place, Model, Price, Like, Time_end, duration, variant, word, cycle]
Index: []

In [174]:
data_30_yes_b = data_final[(data_final['cycle'] != 'no') & (data_final['case_duration'] >= 3) & (data_final['Like'] < 4)]
data_30_yes_b

,ID,Time_start_case,Time_end_case,case_duration,Stage,Time,Channel,Name,Type,Hit,Place,Model,Price,Like,Time_end,duration,variant,word,cycle
1007,П00116,2023-08-22 07:39:35+00:00,2023-08-26 12:39:35+00:00,4.208333,Регистрация претензии,2023-08-22 07:39:35+00:00,Сайт,Геннадий Кривцов,Ответственность перед третьими лицами,Инцидент с 1 автомобилем,Нижний Новгород,Hyundai Kona,553180.0,1,2023-08-22 13:39:35+00:00,360.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
1008,П00116,2023-08-22 07:39:35+00:00,2023-08-26 12:39:35+00:00,4.208333,Проверка документов,2023-08-22 13:39:35+00:00,Сайт,Алексей Лопухин,Ответственность перед третьими лицами,Инцидент с 1 автомобилем,Нижний Новгород,Hyundai Kona,553180.0,1,2023-08-22 22:39:35+00:00,540.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
1009,П00116,2023-08-22 07:39:35+00:00,2023-08-26 12:39:35+00:00,4.208333,Проверка на мошенничество,2023-08-22 22:39:35+00:00,Сайт,Леонид Куликов,Ответственность перед третьими лицами,Инцидент с 1 автомобилем,Нижний Новгород,Hyundai Kona,553180.0,1,2023-08-22 23:39:35+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
1010,П00116,2023-08-22 07:39:35+00:00,2023-08-26 12:39:35+00:00,4.208333,Урегулирование претензии,2023-08-22 23:39:35+00:00,Сайт,Сергей Петров,Ответственность перед третьими лицами,Инцидент с 1 автомобилем,Нижний Новгород,Hyundai Kona,553180.0,1,2023-08-23 17:39:35+00:00,1080.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
1011,П00116,2023-08-22 07:39:35+00:00,2023-08-26 12:39:35+00:00,4.208333,Урегулирование претензии,2023-08-23 17:39:35+00:00,Сайт,Анна Егорова,Ответственность перед третьими лицами,Инцидент с 1 автомобилем,Нижний Новгород,Hyundai Kona,553180.0,1,2023-08-24 17:39:35+00:00,1440.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441459,П09990,2023-04-29 16:36:02+00:00,2023-05-02 20:41:02+00:00,3.170139,Утверждение претензии,2023-05-02 15:41:02+00:00,Офис,Леонид Куликов,Личный ущерб,Боковое столкновение,Сочи,Hyundai Palisade,363035.0,1,2023-05-02 16:41:02+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
441460,П09990,2023-04-29 16:36:02+00:00,2023-05-02 20:41:02+00:00,3.170139,Ремонт автомобиля,2023-05-02 16:41:02+00:00,Офис,Сидоров Илья,Личный ущерб,Боковое столкновение,Сочи,Hyundai Palisade,363035.0,1,2023-05-02 17:41:02+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
441461,П09990,2023-04-29 16:36:02+00:00,2023-05-02 20:41:02+00:00,3.170139,Подготовка итоговой документации,2023-05-02 17:41:02+00:00,Офис,Анна Егорова,Личный ущерб,Боковое столкновение,Сочи,Hyundai Palisade,363035.0,1,2023-05-02 19:41:02+00:00,120.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
441462,П09990,2023-04-29 16:36:02+00:00,2023-05-02 20:41:02+00:00,3.170139,Закрытие страхового случая,2023-05-02 19:41:02+00:00,Офис,Сергей Петров,Личный ущерб,Боковое столкновение,Сочи,Hyundai Palisade,363035.0,1,2023-05-02 20:41:02+00:00,60.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно
441463,П09990,2023-04-29 16:36:02+00:00,2023-05-02 20:41:02+00:00,3.170139,Обзор произошедшего случая,2023-05-02 20:41:02+00:00,Офис,Елизавета Нестерова,Личный ущерб,Боковое столкновение,Сочи,Hyundai Palisade,363035.0,1,2023-05-02 20:41:02+00:00,0.0,"('Регистрация претензии', 'Проверка документов...",ABJDDDDEFGHI,В себя: многократно

In [175]:
data_30_yes_g = data_final[(data_final['cycle'] != 'no') & (data_final['case_duration'] >= 3) & (data_final['Like'] > 3)]
data_30_yes_g

Empty DataFrame
Columns: [ID, Time_start_case, Time_end_case, case_duration, Stage, Time, Channel, Name, Type, Hit, Place, Model, Price, Like, Time_end, duration, variant, word, cycle]
Index: []

In [176]:
like_cycle = data_final_case.groupby(['Like','cycle'])['case_duration'].mean()
like_cycle

Like  cycle
1     no                     1.149228
      В себя: многократно    2.852939
      В себя: разово         1.757042
      Возврат                1.496876
      Пинг-Понг              1.836066
2     no                     1.155874
      В себя: многократно    2.847776
      В себя: разово         1.783253
      Возврат                1.464864
      Пинг-Понг              1.827139
3     no                     1.153645
      В себя: многократно    2.819339
      В себя: разово         1.759455
      Возврат                1.493299
      Пинг-Понг              1.844856
4     no                     1.222423
5     no                     1.224055
Name: case_duration, dtype: float64

In [177]:
work_data = data_23_yes_b.groupby(['cycle', 'word']).count()
work_data

,,ID,Time_start_case,Time_end_case,case_duration,Stage,Time,Channel,Name,Type,Hit,Place,Model,Price,Like,Time_end,duration,variant
cycle,word,,,,,,,,,,,,,,,,,
В себя: многократно,ABJDDDDEFGHI,7944,7944,7944,7944,7944,7944,7944,7944,7944,7944,7944,7944,7944,7944,7944,7944,7944
В себя: разово,ABJDDEFGHI,19260,19260,19260,19260,19260,19260,19260,19260,19260,19260,19260,19260,19260,19260,19260,19260,19260
Возврат,ABCBDEFGHI,5250,5250,5250,5250,5250,5250,5250,5250,5250,5250,5250,5250,5250,5250,5250,5250,5250
Пинг-Понг,ABCBCBDEFGHI,7944,7944,7944,7944,7944,7944,7944,7944,7944,7944,7944,7944,7944,7944,7944,7944,7944

In [178]:
ping_pong = data_23_yes_b[data_23_yes_b['cycle'] == 'Пинг-Понг']
ping_pong_case = data_final_case[(data_final_case['cycle'] == 'Пинг-Понг') & (data_final_case['case_duration'] >= 2) & (data_final_case['case_duration'] < 3) & (data_final_case['Like'] < 4 )]
ping_pong.to_csv('ping_pong.csv', index=False, encoding='utf-8')
ping_pong_case.to_csv('ping_pong_case.csv', index=False, encoding='utf-8')
ping_pong_case

,ID,Time_start_case,Time_end_case,case_duration,Channel,Type,Hit,Place,Model,Price,Like,variant,word,cycle
195,П00023,2023-10-14 23:40:30+00:00,2023-10-16 23:40:30+00:00,2.000000,Сайт,Личный ущерб,Столкновение нескольких автомобилей,Краснодар,Mazda MX-5 Miata RF,147900.0,1,"('Регистрация претензии', 'Проверка документов...",ABCBCBDEFGHI,Пинг-Понг
1407,П00160,2023-05-25 19:53:38+00:00,2023-05-28 02:57:38+00:00,2.294444,Сайт,Ответственность перед третьими лицами,Боковое столкновение,Екатеринбург,Volvo XC60 Recharge,640900.0,2,"('Регистрация претензии', 'Проверка документов...",ABCBCBDEFGHI,Пинг-Понг
1539,П00174,2024-08-04 02:29:33+00:00,2024-08-06 04:32:33+00:00,2.085417,Офис,Личный ущерб,Боковое столкновение,Ижевск,Kia Seltos SX,774690.0,3,"('Регистрация претензии', 'Проверка документов...",ABCBCBDEFGHI,Пинг-Понг
1776,П00201,2023-11-19 05:21:20+00:00,2023-11-21 08:28:20+00:00,2.129861,Сайт,Личный ущерб,Опрокидывание автомобиля,Благовещенск,Subaru Ascent Limited,828240.0,2,"('Регистрация претензии', 'Проверка документов...",ABCBCBDEFGHI,Пинг-Понг
2222,П00252,2023-05-12 05:46:18+00:00,2023-05-14 20:46:18+00:00,2.625000,Сайт,Ответственность перед третьими лицами,Инцидент с 1 автомобилем,Ижевск,Chery Exeed VX,676345.0,3,"('Регистрация претензии', 'Проверка документов...",ABCBCBDEFGHI,Пинг-Понг
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439576,П09777,2024-03-11 15:31:59+00:00,2024-03-13 19:31:59+00:00,2.166667,Электронная почта,Личный ущерб,Переднее столкновение,Нижний Новгород,Jaguar F-Type Coupe,827050.0,1,"('Регистрация претензии', 'Проверка документов...",ABCBCBDEFGHI,Пинг-Понг
439865,П09810,2024-02-14 01:52:59+00:00,2024-02-16 12:57:59+00:00,2.461806,Сайт,Личный ущерб,Заднее столкновение,Барнаул,Chrysler Voyager,316625.0,2,"('Регистрация претензии', 'Проверка документов...",ABCBCBDEFGHI,Пинг-Понг
440355,П09865,2024-11-22 13:43:57+00:00,2024-11-25 03:43:57+00:00,2.583333,Офис,Личный ущерб,Столкновение при боковом движении,Владивосток,Chrysler 300C SRT,407320.0,2,"('Регистрация претензии', 'Проверка документов...",ABCBCBDEFGHI,Пинг-Понг
440984,П09936,2023-03-19 20:15:22+00:00,2023-03-21 23:20:22+00:00,2.128472,Электронная почта,Ответственность перед третьими лицами,Переднее столкновение,Краснодар,Nissan Armada Platinum,166940.0,2,"('Регистрация претензии', 'Проверка документов...",ABCBCBDEFGHI,Пинг-Понг
441236,П09965,2023-04-27 05:12:19+00:00,2023-04-29 07:17:19+00:00,2.086806,Сайт,Личный ущерб,Столкновение при боковом движении,Барнаул,Chery Exeed JET,605540.0,1,"('Регистрация претензии', 'Проверка документов...",ABCBCBDEFGHI,Пинг-Понг

In [179]:
return_in = data_23_yes_b[data_23_yes_b['cycle'] == 'Возврат в себя']
return_in_case = data_final_case[(data_final_case['cycle'] == 'Возврат в себя') & (data_final_case['case_duration'] >= 2) & (data_final_case['case_duration'] < 3) & (data_final_case['Like'] < 4 )]
return_in.to_csv('return_in.csv', index=False, encoding='utf-8')
return_in_case.to_csv('return_in_case.csv', index=False, encoding='utf-8')
return_in_case

Empty DataFrame
Columns: [ID, Time_start_case, Time_end_case, case_duration, Channel, Type, Hit, Place, Model, Price, Like, variant, word, cycle]
Index: []

In [180]:
return_2 = data_23_yes_b[data_23_yes_b['cycle'] == 'Возврат']
return_2_case = data_final_case[(data_final_case['cycle'] == 'Возврат') & (data_final_case['case_duration'] >= 2) & (data_final_case['case_duration'] < 3) & (data_final_case['Like'] < 4 )]
return_2.to_csv('return_2.csv', index=False, encoding='utf-8')
return_2_case.to_csv('return_2_case.csv', index=False, encoding='utf-8')
return_2_case

,ID,Time_start_case,Time_end_case,case_duration,Channel,Type,Hit,Place,Model,Price,Like,variant,word,cycle
0,П00001,2023-09-12 04:32:23+00:00,2023-09-14 14:32:23+00:00,2.416667,Офис,Личный ущерб,ДТП со скрывшимся виновником,Краснодар,Fiat 500X Trekking AWD,128860.0,3,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
1467,П00166,2024-03-22 08:42:38+00:00,2024-03-24 11:44:38+00:00,2.126389,Сайт,Личный ущерб,Боковое столкновение,Тюмень,Fiat 500 1957 Edition,468860.0,2,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
2899,П00330,2024-03-31 16:38:48+00:00,2024-04-02 22:38:48+00:00,2.250000,Сайт,Личный ущерб,Столкновение нескольких автомобилей,Красноярск,Hyundai Palisade Calligraphy AWD,746980.0,1,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
2970,П00338,2024-03-26 06:11:19+00:00,2024-03-28 06:11:19+00:00,2.000000,Сайт,Личный ущерб,Боковое столкновение,Ижевск,Mazda CX-30,794070.0,3,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
4081,П00464,2024-06-16 19:44:16+00:00,2024-06-19 01:44:16+00:00,2.250000,Сайт,Личный ущерб,Опрокидывание автомобиля,Красноярск,Tesla Cybertruck Dual Motor,563465.0,2,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
431305,П08845,2023-02-05 13:37:32+00:00,2023-02-07 16:37:32+00:00,2.125000,Офис,Личный ущерб,Боковое столкновение,Краснодар,Chevrolet Camaro,268175.0,1,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
431511,П08869,2023-02-17 02:54:59+00:00,2023-02-19 07:58:59+00:00,2.211111,Офис,Личный ущерб,Боковое столкновение,Красноярск,Chevrolet Traverse High Country AWD,496995.0,1,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
435573,П09325,2024-02-10 00:05:16+00:00,2024-02-12 05:05:16+00:00,2.208333,Электронная почта,Личный ущерб,Переднее столкновение,Нижний Новгород,Land Rover Defender,779705.0,1,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
437050,П09493,2023-10-09 18:39:55+00:00,2023-10-11 22:44:55+00:00,2.170139,Сайт,Личный ущерб,Заднее столкновение,Нижний Новгород,Chevrolet Traverse,389045.0,1,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат
439088,П09721,2024-10-12 16:38:29+00:00,2024-10-14 20:43:29+00:00,2.170139,Офис,Ответственность перед третьими лицами,Боковое столкновение,Челябинск,Volvo XC70 R-Design,306085.0,3,"('Регистрация претензии', 'Проверка документов...",ABCBDEFGHI,Возврат

In [181]:
return_4 = data_23_yes_b[data_23_yes_b['cycle'] == 'В произвольный этап']
return_4_case = data_final_case[(data_final_case['cycle'] == 'В произвольный этап') & (data_final_case['case_duration'] >= 2) & (data_final_case['case_duration'] < 3) & (data_final_case['Like'] < 4 )]
return_4.to_csv('return_4.csv', index=False, encoding='utf-8')
return_4_case.to_csv('return_4_case.csv', index=False, encoding='utf-8')
return_4_case

Empty DataFrame
Columns: [ID, Time_start_case, Time_end_case, case_duration, Channel, Type, Hit, Place, Model, Price, Like, variant, word, cycle]
Index: []

In [182]:
work_data = data_12_yes_b.groupby(['cycle', 'word']).count()
work_data

,,ID,Time_start_case,Time_end_case,case_duration,Stage,Time,Channel,Name,Type,Hit,Place,Model,Price,Like,Time_end,duration,variant
cycle,word,,,,,,,,,,,,,,,,,
В себя: многократно,ABJDDDDEFGHI,1716,1716,1716,1716,1716,1716,1716,1716,1716,1716,1716,1716,1716,1716,1716,1716,1716
В себя: разово,ABJDDEFGHI,15760,15760,15760,15760,15760,15760,15760,15760,15760,15760,15760,15760,15760,15760,15760,15760,15760
Возврат,ABCBDEFGHI,13280,13280,13280,13280,13280,13280,13280,13280,13280,13280,13280,13280,13280,13280,13280,13280,13280
Пинг-Понг,ABCBCBDEFGHI,6192,6192,6192,6192,6192,6192,6192,6192,6192,6192,6192,6192,6192,6192,6192,6192,6192

In [183]:
operation_01 = data_01_yes_b.groupby(['Stage', 'cycle'])['duration'].mean()
operation_01.head(50)

Stage                             cycle
Закрытие страхового случая        В себя: многократно     93.442623
                                  В себя: разово          89.571429
                                  Возврат                 89.596083
                                  Пинг-Понг               90.234987
Обзор произошедшего случая        В себя: многократно      0.000000
                                  В себя: разово           0.000000
                                  Возврат                  0.000000
                                  Пинг-Понг                0.000000
Подготовка итоговой документации  В себя: многократно     84.590164
                                  В себя: разово          89.220779
                                  Возврат                 88.237454
                                  Пинг-Понг               87.571802
Поиск потерянной документации     Возврат                 89.449204
                                  Пинг-Понг               88.825065
Проверка документов               В себя: многократно    217.426230
                                  В себя: разово         274.501299
                                  Возврат                302.873929
                                  Пинг-Понг              267.487380
Проверка на мошенничество         В себя: многократно     86.557377
                                  В себя: разово          88.909091
Регистрация претензии             В себя: многократно    162.688525
                                  В себя: разово         168.150000
                                  Возврат                170.879437
                                  Пинг-Понг              155.775457
Ремонт автомобиля                 В себя: многократно     88.524590
                                  В себя: разово          88.363636
                                  Возврат                 89.155447
                                  Пинг-Понг               85.691906
Урегулирование претензии          В себя: многократно    214.000000
                                  В себя: разово         353.572727
                                  Возврат                327.127295
                                  Пинг-Понг              177.796345
Утверждение претензии             В себя: многократно     84.590164
                                  В себя: разово          88.324675
                                  Возврат                 90.110159
                                  Пинг-Понг               90.861619
Name: duration, dtype: float64

In [184]:
operation_12 = data_12_yes_b.groupby(['Stage', 'cycle'])['duration'].mean()
operation_12.head(50)

Stage                             cycle
Закрытие страхового случая        В себя: многократно      91.468531
                                  В себя: разово           90.228426
                                  Возврат                  90.768072
                                  Пинг-Понг                90.930233
Обзор произошедшего случая        В себя: многократно       0.000000
                                  В себя: разово            0.000000
                                  Возврат                   0.000000
                                  Пинг-Понг                 0.000000
Подготовка итоговой документации  В себя: многократно      91.888112
                                  В себя: разово           89.352792
                                  Возврат                  88.599398
                                  Пинг-Понг                88.953488
Поиск потерянной документации     Возврат                  90.768072
                                  Пинг-Понг                89.476744
Проверка документов               В себя: многократно     271.902098
                                  В себя: разово          394.305203
                                  Возврат                 395.138554
                                  Пинг-Понг               362.250646
Проверка на мошенничество         В себя: многократно      88.951049
                                  В себя: разово           90.266497
Регистрация претензии             В себя: многократно     162.916084
                                  В себя: разово          191.435279
                                  Возврат                 185.617470
                                  Пинг-Понг               180.819767
Ремонт автомобиля                 В себя: многократно      89.790210
                                  В себя: разово           89.238579
                                  Возврат                  90.677711
                                  Пинг-Понг                89.186047
Урегулирование претензии          В себя: многократно     415.409091
                                  В себя: разово          718.619289
                                  Возврат                1061.070030
                                  Пинг-Понг               704.375969
Утверждение претензии             В себя: многократно      89.370629
                                  В себя: разово           91.180203
                                  Возврат                  89.593373
                                  Пинг-Понг                87.674419
Name: duration, dtype: float64

In [185]:
operation_23 = data_23_yes_b.groupby(['Stage', 'cycle'])['duration'].mean()
operation_23.head(50)

Stage                             cycle
Закрытие страхового случая        В себя: многократно      90.634441
                                  В себя: разово           91.682243
                                  Возврат                  92.800000
                                  Пинг-Понг                90.634441
Обзор произошедшего случая        В себя: многократно       0.000000
                                  В себя: разово            0.000000
                                  Возврат                   0.000000
                                  Пинг-Понг                 0.000000
Подготовка итоговой документации  В себя: многократно      90.634441
                                  В себя: разово           90.685358
                                  Возврат                  95.428571
                                  Пинг-Понг                90.362538
Поиск потерянной документации     Возврат                  92.457143
                                  Пинг-Понг                90.498489
Проверка документов               В себя: многократно     362.981873
                                  В себя: разово          452.386812
                                  Возврат                 575.412381
                                  Пинг-Понг               470.931521
Проверка на мошенничество         В себя: многократно      90.543807
                                  В себя: разово           91.869159
Регистрация претензии             В себя: многократно     183.025680
                                  В себя: разово          205.839564
                                  Возврат                 229.447619
                                  Пинг-Понг               215.259819
Ремонт автомобиля                 В себя: многократно      90.815710
                                  В себя: разово           90.841121
                                  Возврат                  92.114286
                                  Пинг-Понг                93.172205
Урегулирование претензии          В себя: многократно     657.859139
                                  В себя: разово         1121.913292
                                  Возврат                1245.828571
                                  Пинг-Понг              1133.777946
Утверждение претензии             В себя: многократно      89.546828
                                  В себя: разово           90.467290
                                  Возврат                  92.685714
                                  Пинг-Понг                92.990937
Name: duration, dtype: float64

In [186]:
types = data_final_case.groupby('Type')['ID'].count()
types

Type
Личный ущерб                             35919
Ответственность перед третьими лицами    13954
Name: ID, dtype: int64

In [187]:
channel = data_final_case.groupby('Channel')['ID'].count()
channel

Channel
Офис                 14932
Сайт                 31424
Телефон               1025
Электронная почта     2492
Name: ID, dtype: int64

In [188]:
data_cycle_4 = data_final[(data_final['cycle'] == 'В себя: разово') & (data_final['Stage'] == 'Урегулирование претензии')]
data_cycle_min = data_cycle_4.groupby('ID')['Time'].max().reset_index()
data_cycle_min = pd.merge(data_cycle_min, data_cycle_4, how ='left')
data_cycle_min

,ID,Time,Time_start_case,Time_end_case,case_duration,Stage,Channel,Name,Type,Hit,Place,Model,Price,Like,Time_end,duration,variant,word,cycle
0,П00002,2023-07-01 23:20:48+00:00,2023-06-30 17:15:48+00:00,2023-07-03 03:20:48+00:00,2.420139,Урегулирование претензии,Электронная почта,Алексей Лопухин,Личный ущерб,Боковое столкновение,Краснодар,Infiniti QX60 Luxe,110925.0,1,2023-07-02 21:20:48+00:00,1320.0,"('Регистрация претензии', 'Проверка документов...",ABJDDEFGHI,В себя: разово
1,П00012,2024-09-24 06:48:12+00:00,2024-09-23 03:45:12+00:00,2024-09-24 12:52:12+00:00,1.379861,Урегулирование претензии,Офис,Анна Егорова,Личный ущерб,Переднее столкновение,Сочи,Ram 1500 Rebel TRX,457980.0,1,2024-09-24 06:52:12+00:00,4.0,"('Регистрация претензии', 'Проверка документов...",ABJDDEFGHI,В себя: разово
2,П00026,2023-08-20 15:22:27+00:00,2023-08-20 00:18:27+00:00,2023-08-21 20:22:27+00:00,1.836111,Урегулирование претензии,Сайт,Сидоров Илья,Личный ущерб,Переднее столкновение,Сочи,Honda Pilot Elite,183770.0,1,2023-08-21 13:22:27+00:00,1320.0,"('Регистрация претензии', 'Проверка документов...",ABJDDEFGHI,В себя: разово
3,П00029,2023-06-12 03:31:08+00:00,2023-06-11 19:22:08+00:00,2023-06-12 10:33:08+00:00,0.632639,Урегулирование претензии,Офис,Сергей Петров,Личный ущерб,Столкновение при боковом движении,Челябинск,Jaguar F-Type R,801210.0,2,2023-06-12 03:33:08+00:00,2.0,"('Регистрация претензии', 'Проверка документов...",ABJDDEFGHI,В себя: разово
4,П00035,2023-06-22 10:04:32+00:00,2023-06-22 01:57:32+00:00,2023-06-23 14:04:32+00:00,1.504861,Урегулирование претензии,Сайт,Денис Прохоров,Личный ущерб,Инцидент с 1 автомобилем,Нижний Новгород,Chevrolet Traverse RS AWD,544935.0,2,2023-06-23 06:04:32+00:00,1200.0,"('Регистрация претензии', 'Проверка документов...",ABJDDEFGHI,В себя: разово
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5039,П09957,2023-06-10 15:51:33+00:00,2023-06-09 05:51:33+00:00,2023-06-10 20:54:33+00:00,1.627083,Урегулирование претензии,Офис,Елизавета Нестерова,Личный ущерб,ДТП со скрывшимся виновником,Екатеринбург,Mazda MX-5 Miata Club Edition AWD,275570.0,1,2023-06-10 15:54:33+00:00,3.0,"('Регистрация претензии', 'Проверка документов...",ABJDDEFGHI,В себя: разово
5040,П09963,2023-11-17 12:18:30+00:00,2023-11-17 07:12:30+00:00,2023-11-18 17:18:30+00:00,1.420833,Урегулирование претензии,Сайт,Алексей Лопухин,Ответственность перед третьими лицами,Переднее столкновение,Красноярск,Subaru Ascent,491640.0,2,2023-11-18 10:18:30+00:00,1320.0,"('Регистрация претензии', 'Проверка документов...",ABJDDEFGHI,В себя: разово
5041,П09973,2024-09-06 10:30:01+00:00,2024-09-05 16:27:01+00:00,2024-09-06 15:35:01+00:00,0.963889,Урегулирование претензии,Сайт,Инна Смирнова,Личный ущерб,Столкновение при боковом движении,Сочи,Alfa Romeo 4C Spider 2024,532525.0,1,2024-09-06 10:35:01+00:00,5.0,"('Регистрация претензии', 'Проверка документов...",ABJDDEFGHI,В себя: разово
5042,П09982,2023-07-17 10:27:20+00:00,2023-07-15 22:27:20+00:00,2023-07-18 14:27:20+00:00,2.666667,Урегулирование претензии,Сайт,Геннадий Кривцов,Ответственность перед третьими лицами,Инцидент с 1 автомобилем,Красноярск,Subaru Legacy Limited XT,600695.0,1,2023-07-18 08:27:20+00:00,1320.0,"('Регистрация претензии', 'Проверка документов...",ABJDDEFGHI,В себя: разово
5043,П09993,2024-10-22 19:11:06+00:00,2024-10-21 04:11:06+00:00,2024-10-23 17:11:06+00:00,2.541667,Урегулирование претензии,Офис,Семён Афанасьев,Ответственность перед третьими лицами,Инцидент с 1 автомобилем,Краснодар,Jaguar XJL,770185.0,2,2024-10-23 13:11:06+00:00,1080.0,"('Регистрация претензии', 'Проверка документов...",ABJDDEFGHI,В себя: разово

#### Качество работы с зацикленностями сотрудников

In [189]:
top_cadr = data_cycle_min.groupby('Name')['Time'].count().reset_index()
all_cadr = data_cycle_4.groupby('Name')['Time'].count().reset_index()
cadr = pd.merge(top_cadr, all_cadr, on = 'Name', suffixes=['_top', '_all'])
cadr['result'] = cadr['Time_top']/cadr['Time_all']
cadr = cadr.sort_values('result')
cadr

                   Name  Time_top  Time_all    result
10      Михаил Трофимов       124       263  0.471483
12      Семён Афанасьев       338       697  0.484935
5        Денис Прохоров       544      1117  0.487019
6   Елизавета Нестерова       206       420  0.490476
2          Анна Егорова       770      1565  0.492013
14         Сидоров Илья       370       737  0.502035
0       Алексей Лопухин       402       799  0.503129
4      Геннадий Кривцов       304       604  0.503311
13        Сергей Петров       465       922  0.504338
3     Владимир Воробьёв       156       309  0.504854
1         Алёна Волкова       203       401  0.506234
7         Инна Смирнова       346       682  0.507331
9        Леонид Куликов       594      1159  0.512511
8        Ксения Петрова       169       318  0.531447
11      Николай Кабанов        53        95  0.557895

In [190]:
data_pp = data_final[(data_final['cycle'] == 'Пинг-Понг') & (data_final['Stage'] == 'Регистрация претензии')]
#data_cycle_min = data_cycle_4.groupby('ID')['Time'].max().reset_index()
#data_cycle_min = pd.merge(data_cycle_min, data_cycle_4, how ='left')
#data_cycle_min
top_cadr_pp = data_pp.groupby('Name')['Time'].count().reset_index()
top_cadr_pp

                   Name  Time
0       Алексей Лопухин   101
1         Алёна Волкова    51
2          Анна Егорова   243
3     Владимир Воробьёв    45
4      Геннадий Кривцов    82
5        Денис Прохоров   172
6   Елизавета Нестерова    66
7         Инна Смирнова    93
8        Ксения Петрова    60
9        Леонид Куликов   200
10      Михаил Трофимов    37
11      Николай Кабанов    13
12      Семён Афанасьев   104
13        Сергей Петров   169
14         Сидоров Илья   125

In [191]:
data_ppp = data_final[(data_final['cycle'] == 'Пинг-Понг') & (data_final['Stage'] == 'Поиск потерянной документации')]
data_ppp_min = data_ppp.groupby('ID')['Time'].min().reset_index()
data_buf = data_final[['ID','Time','Name']]
data_p = pd.merge(data_ppp_min, data_buf, on = ['ID', "Time"])
bad_search = data_p.groupby('Name')['ID'].count().reset_index().rename(columns={'ID':'Bad_search'})
data_search = data_final[data_final['Stage'] == 'Поиск потерянной документации']
all_search = data_search.groupby('Name')['Stage'].count().reset_index().rename(columns={'Stage':'All_search'})
cadr_search = pd.merge(bad_search, all_search, on = 'Name')
cadr_search['Part: bad/all'] = cadr_search['Bad_search']*100/cadr_search['All_search']
cadr_search = cadr_search.sort_values('Part: bad/all', ascending=True)
cadr_search

                   Name  Bad_search  All_search  Part: bad/all
11      Николай Кабанов           8          48      16.666667
8        Ксения Петрова          45         222      20.270270
4      Геннадий Кривцов          78         377      20.689655
1         Алёна Волкова          56         268      20.895522
6   Елизавета Нестерова          60         275      21.818182
3     Владимир Воробьёв          45         205      21.951220
13        Сергей Петров         135         604      22.350993
7         Инна Смирнова          97         431      22.505800
0       Алексей Лопухин         122         526      23.193916
9        Леонид Куликов         184         765      24.052288
10      Михаил Трофимов          45         187      24.064171
2          Анна Егорова         240         968      24.793388
5        Денис Прохоров         197         790      24.936709
12      Семён Афанасьев         110         420      26.190476
14         Сидоров Илья         139         523      26.577438

In [192]:
data_ppp_max = data_ppp.groupby('ID')['Time'].max().reset_index()
data_ppp_max = data_ppp_max.rename(columns={'Time': 'Time_max'})
data_ppp_min = pd.merge(data_ppp_min, data_buf, how ='left')
data_ppp_max = pd.merge(data_ppp_max, data_buf, how ='left')

data_ppp_min

          ID                       Time                 Name
0     П00018  2023-09-03 07:24:00+00:00     Геннадий Кривцов
1     П00023  2023-10-15 10:40:30+00:00       Денис Прохоров
2     П00041  2024-02-19 22:40:35+00:00        Инна Смирнова
3     П00093  2024-02-15 17:08:18+00:00  Елизавета Нестерова
4     П00133  2024-12-24 20:34:50+00:00      Семён Афанасьев
...      ...                        ...                  ...
1556  П09810  2024-02-14 11:57:59+00:00         Анна Егорова
1557  П09865  2024-11-23 05:43:57+00:00         Анна Егорова
1558  П09935  2024-02-22 23:00:12+00:00       Леонид Куликов
1559  П09936  2023-03-20 02:18:22+00:00      Николай Кабанов
1560  П09965  2023-04-27 09:17:19+00:00      Семён Афанасьев

[1561 rows x 3 columns]

In [193]:
ppp_min = data_ppp_min.groupby('Name')['ID'].count().reset_index()
ppp_min

                   Name   ID
0       Алексей Лопухин  122
1         Алёна Волкова   56
2          Анна Егорова  240
3     Владимир Воробьёв   45
4      Геннадий Кривцов   78
5        Денис Прохоров  197
6   Елизавета Нестерова   60
7         Инна Смирнова   97
8        Ксения Петрова   45
9        Леонид Куликов  184
10      Михаил Трофимов   45
11      Николай Кабанов    8
12      Семён Афанасьев  110
13        Сергей Петров  135
14         Сидоров Илья  139

In [194]:
ppp_max = data_ppp_max.groupby('Name')['ID'].count().reset_index()
ppp_max

                   Name    ID
0       Алексей Лопухин  1404
1         Алёна Волкова   714
2          Анна Егорова  2841
3     Владимир Воробьёв   556
4      Геннадий Кривцов  1055
5        Денис Прохоров  2158
6   Елизавета Нестерова   837
7         Инна Смирнова  1262
8        Ксения Петрова   659
9        Леонид Куликов  2204
10      Михаил Трофимов   502
11      Николай Кабанов   161
12      Семён Афанасьев  1236
13        Сергей Петров  1674
14         Сидоров Илья  1469